### ISSUE TITLE
Conflicts with Reachability 

### ISSUE THREAD

**Issue by mohpor** [dustturtle/RealReachability#1]
Hi,
I have always wanted this. To be notified about true connections.

After finding this repo, I tried to add it to one of my existing projects. The project has many many dependencies which in turn have their own dependencies and from there it goes a downward spiral ... anyway, somewhere along the way, one of these projects has Reachability as its dependency. Now, I can't remove the main dependency (not for the time being at least).

When I added RealReachability to my project, i have faced a conflict between RealReachability and Reachability on the `NetworkStatus` enum cases: 

```objc
typedef NS_ENUM(NSInteger, NetworkStatus) {
    // Apple NetworkStatus Compatible Names.
    NotReachable = 0,
    ReachableViaWiFi = 2,
    ReachableViaWWAN = 1
};
```

Is it possible to change the enum cases for the unlucky guys like me who want to keep Reachability and RealReachability coexist in one project?

**Comment by dustturtle** [comment]
Thank you very much! I will fix this issue as soon as possible! As you wish, I will change my enum name to solve this conflict.

**Comment by mohpor** [comment]
That'll be great.

**Comment by mohpor** [comment]
While you're at it, I strongly suggest that you start a sample project and include both frameworks to make sure there's no other conflicts I still haven't found.

**Comment by dustturtle** [comment]
Sure I must do this test. I will do that in one day. ^_^ Thank you for your reminder!

**Comment by dustturtle** [comment]
Done. Later I will update the .md and pod version. Enjoy it!
