### ISSUE TITLE
真机调试下，关闭数据流量，通过上滑打开关闭wifi

### ISSUE THREAD

**Issue by BarryGuo** [dustturtle/RealReachability#10]
打开wifi，几乎每次都先回调wifi，然后回调无网络
关闭wifi，因为之前已经回调了无网络，不进行回调。

**Comment by dustturtle** [comment]
网络连通性不变的情况下，不会进行回调的，因为网络连接的实际可达性没有变化啊。你提到的另外一个优化点，之前已经考虑了，正在开发中，谢谢

**Comment by dustturtle** [comment]
你这里主要的疑问是什么？ 也可以邮件到openglnewbee@163.com ^_^

**Comment by dustturtle** [comment]
not an issue. designed to act like that.
