### ISSUE TITLE
iOS11监测不准

### ISSUE THREAD

**Issue by colaicode** [dustturtle/RealReachability#100]
如题

**Comment by dustturtle** [comment]
请描述具体的场景和行为

**Comment by sauchye** [comment]
iOS 11 无网络下监测，无法监测出无网络，切换打开关闭网络，无法监测到

**Comment by dustturtle** [comment]
iOS11真机实测没有上述问题，一切正常。是不是没有允许app网络访问或者模拟器测试 @sauchye @colaicode
