### ISSUE TITLE
无线是打开的，包括app的网络也是打开的  但是在接受通知的时候提示没有网

### ISSUE THREAD

**Issue by padishahG** [dustturtle/RealReachability#102]
![img_0181](https://user-images.githubusercontent.com/22125316/33194027-d3babcca-d107-11e7-858f-065360eb143d.PNG)
<img width="238" alt="a947f9b1-a40f-49bf-aa7d-11ed71e177b8" src="https://user-images.githubusercontent.com/22125316/33194037-e81e8606-d107-11e7-86e6-6c17fa6eb95d.png">

**Comment by dustturtle** [comment]
43分16秒的错误日志是什么？ 初始化什么的都正常嘛

**Comment by padishahG** [comment]
@dustturtle   这个前段时间用起来妥妥的，后来过了一段时间之后发现监测网络异常（网络切换接受不到通知）。43分16秒报404错误。

**Comment by padishahG** [comment]
@dustturtle 要不要把demo给你？

**Comment by padishahG** [comment]
- (void)viewDidLoad {
    [super viewDidLoad];
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(networkChanged:)
                                                 name:kRealReachabilityChangedNotification
                                               object:nil];
  
}
- (void)viewWillAppear:(BOOL)animated{
    [super viewWillAppear:YES];
    [self judgeNet];
}
- (void)judgeNet
{

    ReachabilityStatus status = [GLobalRealReachability currentReachabilityStatus];
    switch (status) {
        case RealStatusNotReachable:
            [self.view addSubview: [self.myAlertView show]];
            break;
        case RealStatusViaWiFi:
            [self.myAlertView removeAllView];;
            break;
        case RealStatusViaWWAN:
            [self.myAlertView removeAllView];;
            break;
        default:
            break;
    }
}
- (void)networkChanged:(NSNotification *)notification
{
    RealReachability *reachability = (RealReachability *)notification.object;
    ReachabilityStatus status = [reachability currentReachabilityStatus];
    switch (status)
    {
        case RealStatusNotReachable:
        {
             [self.view addSubview: [self.myAlertView show]];
            break;
        }
        case RealStatusViaWiFi:{
             [self.myAlertView removeAllView];;
            break;
        }
        case RealStatusViaWWAN:{
             [self.myAlertView removeAllView];;
            break;
        }
        default:
            break;
    }
}
- (NoNetWorkView *)myAlertView{
    if(_myAlertView ==nil){
        _myAlertView = [NoNetWorkView sharedAlertView];
    }
    return _myAlertView;
}

**Comment by dustturtle** [comment]
接收到失败通知后一段时间能否自动恢复？也可能是偶现的ping操作失败

**Comment by padishahG** [comment]
是不是因为我升级过手机最新系统的原因。两个工程现在都是这种问题。不能自动恢复

**Comment by dustturtle** [comment]
我这里也是最新系统啊，没有遇到你说的问题，是必现的吗？多久出现？

**Comment by padishahG** [comment]
嗯呢   现在一直是这个样子   大佬 上面的代码使用正确的吧？

**Comment by dustturtle** [comment]
代码看起来没有问题啊，还有个就是appdelegate里面加个开始监听的就行了

**Comment by padishahG** [comment]
好的  谢谢  我明天试试。

**Comment by padishahG** [comment]
还是不行呢？

**Comment by dustturtle** [comment]
openglnewbee@163.com  demo发到我邮箱我可以调试看看

**Comment by yunjinghui123** [comment]
同样的问题，网络通过终端ping也是没有问题的，但是会莫名其妙的返回没网络状态

**Comment by o0oi1i** [comment]
同问

**Comment by dustturtle** [comment]
master上的最新版本引入了double check机制，可以设置两个ping地址，通过双地址+重试来保证可靠性，欢迎体验，谢谢～ 可以试下问题是否还存在

**Comment by unkosun** [comment]
我们使用了最新的double check机制的代码，还是有这个问题。ping 都是超时，其实是可以访问网络的，在App 内可以打开网页访问网络。

**Comment by dustturtle** [comment]
@unkosun 概率高吗？出问题的设备当时的网络状况怎么样？

**Comment by unkosun** [comment]
> @unkosun 概率高吗？出问题的设备当时的网络状况怎么样？
概率不是很高，设备，iPhone X和iPhone 7P 都出现过。

**Comment by liulei6415** [comment]
博主你好,我下载的demo也遇到了同样的问题,在WiFi环境下,ping的时候会超时. 网络状态变成:RealStatusNotReachable.

**Comment by dustturtle** [comment]
> 博主你好,我下载的demo也遇到了同样的问题,在WiFi环境下,ping的时候会超时. 网络状态变成:RealStatusNotReachable.

是偶现的还是说这个wifi一定会出现

**Comment by padishahG** [comment]
@dustturtle 看来不是我遇到这个问题  哈哈哈

**Comment by unkosun** [comment]
@dustturtle 我们出现ping超时问题的时候，都是WIFI网络，而且是在不同的WIFI场景（公司和用户家里都出现了）

**Comment by dustturtle** [comment]
> @dustturtle 我们出现ping超时问题的时候，都是WIFI网络，而且是在不同的WIFI场景（公司和用户家里都出现了）

可以检查下出问题的路由是否禁用了icmp

**Comment by dustturtle** [comment]
那我理解当时的网络状态可能比较差？否则double check不同的地址应该极大概率成功啊

**Comment by unkosun** [comment]
> 那我理解当时的网络状态可能比较差？否则double check不同的地址应该极大概率成功啊

如果是网络状态差的话，无法解释，ping超时返回RealStatusNotReachable，但是应用内还是可以正常打开网页

**Comment by dustturtle** [comment]
> > 那我理解当时的网络状态可能比较差？否则double check不同的地址应该极大概率成功啊
> 
> 如果是网络状态差的话，无法解释，ping超时返回RealStatusNotReachable，但是应用内还是可以正常打开网页
一般来说下个ping周期就会自动恢复。丢包率和时延均可能导致ping失败的。http请求的情况不太一样
