### ISSUE TITLE
经常有网的情况下提示也是网络连接失败

### ISSUE THREAD

**Issue by TabCen** [dustturtle/RealReachability#104]
放弃

**Comment by OCer** [comment]
用AFN的解决了  不过AFN的也有一个问题，在application:didFinishLaunchingWithOptions:里面获取不到网络状态；最少要到applicationDidBecomeActive:才可以

**Comment by dustturtle** [comment]
要检测是否连接网络使用localconnection就可以了，这个适用于实时性高、检测弱网络的场景
