### ISSUE TITLE
Background mode?

### ISSUE THREAD

**Issue by claesjacobsson** [dustturtle/RealReachability#108]
Hi and thanks for a fine library! 

How does it work when the app is in background mode?

Thanks!

**Comment by dustturtle** [comment]
It works with your project, you don't need do extra things with this framework. If your app support background running, it works with your app. You can observe the behavior with some logs to file system in your project.

**Comment by claesjacobsson** [comment]
Thanks!

**Comment by claesjacobsson** [comment]
To use `[GLobalRealReachability currentReachabilityStatus]`, must I first call `[GLobalRealReachability startNotifier]` ?

**Comment by claesjacobsson** [comment]
My app only supports background modes  for remote notifications and background fetch. I can't seem to get it to work with the reachability notifications. As soon as I open the app the notification is processed.

**Comment by dustturtle** [comment]
1. Before you do any action by this framework you should 'start notifier'.
2. I think maybe you do not need to stop the notifier. Observing all the time is the common situation.
If you do not want the check action occur too often , you can set this: "autoCheckInterval".
The common use is to observe "kRealReachabilityChangedNotification" after start notifier Asynchronously.

In my opinion, remote notification and background fetch do not mean your app still working on the background. Instead , they are all handled by the system. I am not sure about your user case, why we need this here, in background fetch?

**Comment by claesjacobsson** [comment]
The thing is, my app is running in the background. It performs other tasks which I can see in the console. But it does not respond to kRealReachabilityChangedNotification until I open the app.

**Comment by dustturtle** [comment]
This way, I suggest you call the "currentReachabilityStatus" in your delegate method.
 The background mode now you are facing is not reliable for notifications, in my opinion.

**Comment by claesjacobsson** [comment]
My app receives remote notifications. I can see that code handled in the background. But when I connect to a WiFi network, the kRealReachabilityChangedNotification doesn't seem to be sent until I open the app.

**Comment by dustturtle** [comment]
That is different. You can not control this in your app. You may consider my advice or go to some sessions by apple about how background works in iOS apps. Good luck to you!

**Comment by dustturtle** [comment]
Hi, claes. I asked the question  to apple engineers in the WWDC 2018 lab which you you ask to me about the background stuffs. So the answer is the same: please do the check in the delegates (sync invoke to get the network status). They can not ensure the notification be triggered in your user case.
