### ISSUE TITLE
从后台到前台会有crash的问题，请问下这是为什么呢

### ISSUE THREAD

**Issue by haojian2016** [dustturtle/RealReachability#11]
![3e5c5627-a7c4-4497-93d1-8bdac39ceeae](https://cloud.githubusercontent.com/assets/16795422/13559754/6c313d70-e452-11e5-8d97-03354bb0b075.jpeg)

INFO: Reveal Server started (Protocol Version 25).
Assertion failed: (theHost == obj->_host), function HostResolveCallback    file /Users/.../trunk/Pods/RealReachability/RealReachability/Ping/PingFoundation.m, line 575.

**Comment by dustturtle** [comment]
什么版本的iOS设备？出现的频率高吗？ 也可能跟你工程本身有关。你可以尝试注释掉这两句assert，看看是否还有问题发生？
期待您的回复。 openglnewbee@163.com
PS:这里是苹果代码的断言导致的crash,debug的时候会挂，distribution则不会。

**Comment by haojian2016** [comment]
好的，那我注释掉试试，主要测的是8，频率不高，偶尔会崩溃

**Comment by dustturtle** [comment]
好的，那麻烦你试一下告诉我，多谢。如果注释后还crash我就去找一部iOS8设备调调看。

**Comment by haojian2016** [comment]
![Uploading 7EF74462-7D72-4233-A12C-B62C7CDD9634.png…]()

光注释掉assert的话，会出现上面的情况，然后我现在就给断言做了个判断，不成立就return掉，程序不会crash的，这个出现的几率很小，是不是在内存大的时候会出现异常呢？

**Comment by haojian2016** [comment]
![Uploading 7EF74462-7D72-4233-A12C-B62C7CDD9634.png…]()
光注释掉assert的话，会出现这种的情况，然后我现在就给断言做了个判断，不成立就return掉，程序不会crash的，这个出现的几率很小，是不是在内存大的时候会出现异常呢？

**Comment by haojian2016** [comment]
光注释掉assert的话，会出现这种的情况，然后我现在就给断言做了个判断，不成立就return掉，程序不会crash的，这个出现的几率很小，是不是在内存大的时候会出现异常呢？
![7ef74462-7d72-4233-a12c-b62c7cdd9634](https://cloud.githubusercontent.com/assets/16795422/13562850/a4e630d8-e477-11e5-9eac-c2cd15aac613.png)

**Comment by dustturtle** [comment]
非常感谢你的反馈！ 如果有条件的话能否测试 9.0的设备是否也可能出问题？
场景就只有前后台切换吗？ demo工程方便的话可以发给我调试看看。
openglnewbee@163.com  谢谢！

**Comment by dustturtle** [comment]
请告诉我你的系统版本号

**Comment by haojian2016** [comment]
xcode7.2.1，我自己写了一个demo，就是光检测网络的，没发现问题，我感觉应该是内存问题，我再看看

**Comment by ShantiSR** [comment]
any solution?, I have the same problem with Xcode 7.2.1. Thank you

**Comment by dustturtle** [comment]
iOS device version? ig: 9.1, in my 9.2 version device, this never happened

**Comment by ShantiSR** [comment]
At the moment only in the Simulator with iOS 9.1, 9.0, and iOS 8

**Comment by dustturtle** [comment]
Thank you! I will be deep into it.

**Comment by dustturtle** [comment]
I have committed some codes to fix the problem. Please try and give me a feedback. Thank you all!

**Comment by ShantiSR** [comment]
Now it always says that there is no internet connection, even with your test project:
![captura de pantalla 2016-03-10 a las 11 45 58](https://cloud.githubusercontent.com/assets/3288528/13667230/b5d9bf78-e6b5-11e5-8623-9bc381825304.png)

**Comment by dustturtle** [comment]
I have made a silly mistake.>_<  now please try again. Thank you! @ShantiSR

**Comment by ShantiSR** [comment]
Now it works perfectly, thank you very much for everything @dustturtle

**Comment by dustturtle** [comment]
You are welcome! I am so glad to meet kindly people like you! Thank you so much! @ShantiSR

**Comment by dustturtle** [comment]
@haojian2016 能否有空帮忙试下master最新的代码哈？多谢了

**Comment by haojian2016** [comment]
嗯，好哒，嘿嘿

**Comment by ShantiSR** [comment]
If I launch the app without internet connection, the app is broken:

![captura de pantalla 2016-03-11 a las 11 04 37](https://cloud.githubusercontent.com/assets/3288528/13699287/b4d18362-e779-11e5-81fc-b928462bd728.png)

**Comment by dustturtle** [comment]
@ShantiSR fixed it.Thank you so much!

**Comment by ShantiSR** [comment]
@dustturtle Thank you very much, working properly :)

**Comment by dustturtle** [comment]
@haojian2016 有结果了吗？看到帮忙回复下哈！ 多谢！

**Comment by dustturtle** [comment]
fixed
