### ISSUE TITLE
龟速网络问题

### ISSUE THREAD

**Issue by miniLV** [dustturtle/RealReachability#110]
龟速网络下(假设1k/s的网速)，进行网络连接，所有的app，包括uc，各种其他浏览器都提示“联网失败，请检查网络”，但是还是进入```case RealStatusViaWiFi:
            {
                self.alert.message = @"Do what you want! free!";
}```这个判断，显示对应的提示，无法获取 - “没有网络”的状态

**Comment by dustturtle** [comment]
返回ok说明可以ping通，并不代表网速的快慢

**Comment by miniLV** [comment]
但是在该网络环境下，用各种浏览器请求“www.baidu.com”，包括该wifi下用多个app(京东、微信、美团等)发送请求，都显示网络异常，没有一个是请求成功的

**Comment by dustturtle** [comment]
你是用proxy之类的工具做的限流？ 要知道此类工具只针对http，icmp协议可以正常作用

**Comment by miniLV** [comment]
@dustturtle 是测试连了龟速wifi，然后测app的时候出现了我所描述的问题，又因为app只用了简单的AVPlaer直接播放在线音乐，没用`AFN`实现网络下载，所以没办法通过请求时长进行判断，不过目前已经接近了，3q~
