### ISSUE TITLE
VPN状态下为什么忽略ping结果

### ISSUE THREAD

**Issue by JpacheGitHub** [dustturtle/RealReachability#111]
我也在做类似的需求, 直接用的SimplePing, 发现VPN状态下, ping返回的包是不能被解读的...为什么会这样, 有什么好的解决方案吗? 自己手机在用shadowrocket上Google, 他的 ping 可以 ping 通啊...

**Comment by JpacheGitHub** [comment]
其实是ping通了, 就是接收到的数据是异常数据包...这我是不是应该处理成ping成功了, 正常计算延迟就行

**Comment by dustturtle** [comment]
因为vpn不代理icmp的数据包，ping的结果不能代表http的连通性（后者是用户所关注的），因此直接忽略之以避免较大概率的误判。

**Comment by JpacheGitHub** [comment]
网上看到这段
VPN的隧道协议主要有三种，PPTP、L2TP和IPSec
也就是说, 如果想做VPN的ping, 至少要做这三种才会比较通用, 因为VPN使用的协议不是统一的? 只能对应各种协议去解析数据包才行?

**Comment by dustturtle** [comment]
vpn的协议很多，现在ss也很流行的。使用vpn的情况比较复杂，我这里作为一个相对通用的工具，倾向于简单可靠的解决方案，不会去深入vpn的具体协议去做开发

**Comment by JpacheGitHub** [comment]
好吧, 懂得了...谢谢你啦, 之前想都不知道往哪里想
