### ISSUE TITLE
检测有问题

### ISSUE THREAD

**Issue by goodcyg** [dustturtle/RealReachability#112]
我下载demo，设置如下，其他没有改，提示没有网络，其实www.youtube.com是可以访问的：
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    GLobalRealReachability.hostForPing = @"www.youtube.com";
    GLobalRealReachability.hostForCheck = @"www.youtube.com";
    [GLobalRealReachability startNotifier];
    return YES;
}

**Comment by goodcyg** [comment]
提示：
Nothing to do! offlineMode

**Comment by goodcyg** [comment]
youtube.com不支持ping

**Comment by dustturtle** [comment]
这个host不能随便填的，很多服务器不支持ping。选择1: 常见的支持ping的速度较好的网站; 选择2:你的服务器且支持ping
