### ISSUE TITLE
WIFI助手这类的监听问题

### ISSUE THREAD

**Issue by hatjs880328s** [dustturtle/RealReachability#113]
监听结果首先会返回一个   wifi，然后过了一段时间会返回 无连接
请问这种情况是设计吗？ 还是BUG？

**Comment by dustturtle** [comment]
设计就是这样的，一开始是本地状态的监听（wifi可用），后面发现ping不通所以就返回无连接了

**Comment by hatjs880328s** [comment]
@dustturtle   谢谢。
