### ISSUE TITLE
iOS12 网络延迟问题，系统SCNetworkReachabilityRef可能有问题

### ISSUE THREAD

**Issue by Cellphoness** [dustturtle/RealReachability#114]
iOS12 网络延迟问题，断网和连WIFI之间测试，有时网络状态返回是前一次的结果 ，有时候doubleCheck之后，返回的是正常，又或者偶尔有网络的变化检测不出，过大概几分钟又恢复正常。目前这个基于ping和SCNetworkReachabilityRef，已经是比较好的解决方案。最头痛的是在iOS12下，苹果官方给的Reachability也是只要一断网，后面的网络状态就检测不出来了，但是iOS11,10,9全部都没有这样的问题。我想应该是苹果底层的网络框架有改动了，又没有放出对应的替换API！！！

**Comment by dustturtle** [comment]
能否再具体描述问题的场景呢？非常的感谢！
iOS12有新的框架和方法出现的，不过新方法仅iOS12有效。如果有需要我会尽快实现一个demo出来

**Comment by dustturtle** [comment]
“只要一断网，后面的网络状态就检测不出来了” 这个怎么理解哈？ 我可以通过什么步骤尝试重现呢？

**Comment by Cellphoness** [comment]
“只要一断网，后面的网络状态就检测不出来了”， 这个描述不是你的这个框架，是那个2015最后更新Reachability库，这个只要一断网就不会在发出网络变化的通知。

**Comment by Cellphoness** [comment]
如果说这个框架的问题，我新建了一个空白工程测试的。我发现比较明显的是，在iOS12的下模拟器 iPhone XR，第一次的网络变化没有检测出，第二次开始检测出来了，可是返回的网络状态是第一次的。重现如下：
1、在有连WIFI的场景下启动  
2、启动后，断开WIFI  
3、（等待10秒以上） 没有检测出没有网络
4、再次连上WIFI
5、两到三秒后网络恢复了，检测出来的是 RealStatusNotReachable，无网络
6、再关闭WIFI 此时检测出 RealStatusViaWiFi，隔了大概一秒，返回了RealStatusNotReachable
7，再次连上WIFI
8、此时没有检测出网络已经恢复，以上

3、5、8下是出现异常的，整理如下，iOS12调试结果，首次的网络变化没有检测出，每隔一次网络检测都会检测不出来，但下一次断网或者连上WIFI就可以检测出，最后一次出现的状态是对的，前一次的结果也会出现。

**Comment by Cellphoness** [comment]
如果我这边有空的话，也会看下怎么针对iOS12，替换API，优化代码

**Comment by dustturtle** [comment]
在真机上有没有类似的场景？一般来说和设备相关的能力还是要以真机测试的结果为依据，模拟器的不太可靠

**Comment by Cellphoness** [comment]
我的问题，我在真机iPhone6s Plus 12.0.1 还有 iPhone 6 12.1上 测试正常。但是，之前12.0刚出的时候iPad真机是异常，最近都是做iPad的，iPad12.0以上的设备我这已经没了，无法测试。

**Comment by dustturtle** [comment]
好的，非常感谢！
