### ISSUE TITLE
貌似存在关于double check不能本质解决正确获取当前的网络状态的问题

### ISSUE THREAD

**Issue by beichenming** [dustturtle/RealReachability#116]
您好，我们在项目发现了一个RealReachability的问题，是关于double check的机制问题；
  问题现象是这样的：我们利用double check的方式，在项目中增加了apple以及baidu两个域名进行ping的操作，但是存在一定的概率两个都无法ping成功（概率比较小）；所以当这种情况发生的时候，当前的网络就会显示无法连接；
  我知道您可能会说是网络波动造成的，但是我们check过当发生这种现象的时候，微信等App并没有提示断网（因为本身网络就是正常的）；

我们在RealReachability中打印了相关的日志，从日志中可以看到中间失败过三次cehck，之后又恢复了正常（我怀疑是由于check超时所以引起的）。

所以我觉得double check只能避免类似情况的出现，但是不能根治check失败这种情况。谢谢

![default](https://user-images.githubusercontent.com/6540985/49199148-5edc2400-f3d1-11e8-8154-aa14fa2ccfbf.png)

**Comment by dustturtle** [comment]
app的提示（比如微信）只会在local connection不可用或者本身刷新或者请求连接失败的情况下才会发生；这不代表在空闲时间网络连接状况一直是很好的
