### ISSUE TITLE
tag 1.3.0 podspec内的版本号却是1.2.2

### ISSUE THREAD

**Issue by wangshiyu13** [dustturtle/RealReachability#117]
tag 1.3.0 podspec内的版本号却是1.2.2

**Comment by dustturtle** [comment]
这个版本号是作者自己使用提交到cocoapods用的，我认为它对用户来说是没有用处的（安装的时候指定版本号就行）。这个跟我提交的流程有关，如果觉得有必要改，请指出价值在何处，谢谢～！

**Comment by wangshiyu13** [comment]
这个对pod packager打包不太友好，会造成制定版本和实际版本号不一致




| |
汪诗雨
|
|
邮箱：wangshiyu13@163.com
|

签名由 网易邮箱大师 定制

在2018年12月25日 15:56，Zhenwei Guan 写道：

这个版本号是作者自己使用提交到cocoapods用的，我认为它对用户来说是没有用处的（安装的时候指定版本号就行）。这个跟我提交的流程有关，如果觉得有必要改，请指出价值在何处，谢谢～！

**Comment by dustturtle** [comment]
之所以这里的文件delay一个版本是因为提交新版本的时候里面的podspec是上一个版本的。这个文件不放在里面也不影响，只是我自己放在这里维护了。

**Comment by dustturtle** [comment]
好的，后续发布的时候我会注意先升级这个。

**Comment by wangshiyu13** [comment]
谢谢！




| |
汪诗雨
|
|
邮箱：wangshiyu13@163.com
|

签名由 网易邮箱大师 定制

在2018年12月25日 15:59，Zhenwei Guan 写道：

好的，后续发布的时候我会注意先升级这个。
