### ISSUE TITLE
多次调用的问题

### ISSUE THREAD

**Issue by j364960953** [dustturtle/RealReachability#12]
- (void)networkChanged:(NSNotification *)notification
{

}
这个方法会调用多次。切换网络的时候

**Comment by dustturtle** [comment]
这个在伪连接的场景下，就会被调用2次。先返回本地连接的结果，异步返回ping的结果（ping的结果和本地连接结果不一致的情况～从体验最优化的角度考虑，此策略更佳）。
正常场景是不会被调用多次的，除非网络连接状态本身不稳定。
若还有疑问可以发邮件给我: openglnewbee@163.com. 谢谢。
