### ISSUE TITLE
Ping always fails in iOS 12

### ISSUE THREAD

**Issue by houjiahui90** [dustturtle/RealReachability#124]
The version I used was 1.3.0. When I used it on a non-WiFi network, Ping always failed. Before failing, I threw the following error:

2019-04-12 16:29:13.833564+0800 xxxxxx[3166:844815] [NetworkInfo] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x280b58500, domain=1, instance=1>

Is it because the iOS version is upgraded that the API that was originally available becomes unavailable because of the privilege problem?

**Comment by houjiahui90** [comment]
Sorry, I just debug for a long time before I found that SDK had no problem. I don't know why only the network of that cell phone could cause Socket requests to be sent but could not execute'readCallBack'. I guess it's the operator's problem, so I closed the issue.

**Comment by dustturtle** [comment]
Thanks a lot! Keep in touch~
