### ISSUE TITLE
RealReachability Crash SomeTimes

### ISSUE THREAD

**Issue by CoderCMY** [dustturtle/RealReachability#126]
In My App, Bugly Reports some crashes about  RealReachability
`
libsystem_kernel.dylib | __sendto + 8
1 RealReachability | -[PingFoundation sendPingWithData:] (PingFoundation.m:313)
2 RealReachability | -[PingHelper pingFoundation:didStartWithAddress:] (PingHelper.m:159)
3 RealReachability | -[PingFoundation startWithHostAddress] (PingFoundation.m:670)
4 RealReachability | -[PingFoundation hostResolutionDone] (PingFoundation.m:723)
5 RealReachability | HostResolveCallback (PingFoundation.m:763)
`

**Comment by dustturtle** [comment]
有完整的crash日志吗，可以发我邮箱 openglnewbee@163.com
使用的哪个版本的realreachability

**Comment by CoderCMY** [comment]
> 有完整的crash日志吗，可以发我邮箱 [openglnewbee@163.com](mailto:openglnewbee@163.com)
> 使用的哪个版本的realreachability

邮件已发，请大佬查阅

**Comment by dustturtle** [comment]
@CoderCMY 之前修改后还有问题吗？我发你的代码

**Comment by CoderCMY** [comment]
抱歉，大佬，没来得及验证，我们是做免费小说的，项目内有监测网络连通性的需求，有网络的话定时送金币给用户，用了RealReachability后，部分用户反馈家里的WiFi是通的，应用内也能上网，但是库里面的网络连通性方法一直返回未联网，影响了这块逻辑，所以后来替换为了ReachabilitySwift这个库


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhenwei Guan"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月19日(星期二) 中午11:18
收件人:&nbsp;"dustturtle/RealReachability"<RealReachability@noreply.github.com&gt;;
抄送:&nbsp;"MiaoMiao@Ming"<858626566@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dustturtle/RealReachability] RealReachability Crash SomeTimes (#126)




@CoderCMY 之前修改后还有问题吗？我发你的代码

**Comment by dustturtle** [comment]
有个别路由器在默认设置里面会禁ping。。。

**Comment by dustturtle** [comment]
有个朋友pull request做了个http版本的探测

**Comment by fantexi023** [comment]
> @CoderCMY 之前修改后还有问题吗？我发你的代码

俺也遇到了同样的问题，请问这个问题有修复吗？
