### ISSUE TITLE
5G not working

### ISSUE THREAD

**Issue by bekzodrakhmatof** [dustturtle/RealReachability#133]
Hi Team,

I am using latest version 1.4.1 on my app. But when I use 5G it is sending RealStatusNotReachable result. Although my Networking API is working correctly.

Please support us with this issue.

Thank you!

![IMG_1B515300212B-1](https://user-images.githubusercontent.com/23249828/124692668-efc7f400-df18-11eb-942b-d6e24083d6b5.jpeg)

**Comment by dustturtle** [comment]
this only occur when you are using 5g? how about change the network to 4g?

**Comment by dustturtle** [comment]
@bekzodrakhmatof

**Comment by bekzodrakhmatof** [comment]
It works with 4G
