### ISSUE TITLE
首次进入时候 (void)networkChanged监听错误

### ISSUE THREAD

**Issue by afanti100** [dustturtle/RealReachability#14]
问题描述：在某个页面注册监听，如果当前网络是3G并且开WIFI，那么会必然进入networkChanged，其实网络本身并没有发生变化，不应当进入networkChanged回调函数

**Comment by dustturtle** [comment]
可以给个联系方式吗？ 了解下具体情况，谢谢  openglnewbee@163.com

**Comment by afanti100** [comment]
你好

**Comment by afanti100** [comment]
已经给你发邮件了，谢谢
我的邮箱:peng.han@lejent.com

**Comment by afanti100** [comment]
也可以加我qq:492798697

**Comment by dustturtle** [comment]
我加你qq了，邮件没收到哈。qq聊

**Comment by dustturtle** [comment]
看到了通过一下哈，qq交流下 @afanti100

**Comment by thereqwe** [comment]
我也很纳闷,默认第一次就进入networkChanged

**Comment by thereqwe** [comment]
我q523489996

**Comment by dustturtle** [comment]
已经修复。初始化状态时不再发送状态变化通知（master上最新代码）。
