### ISSUE TITLE
No normal status matched, return unreachable temporary

### ISSUE THREAD

**Issue by sun-fox-cj** [dustturtle/RealReachability#15]
It tells me "No normal status matched, return unreachable temporary" when I debug my app on my phone, I have no idea, what's wrong with it

**Comment by dustturtle** [comment]
That means " RRStateInvalid  or RRStateUnloaded ". That means the reachability is not working normally. Would you please tell me more about what you do with you app? or send your demo to me?
Thank you!  openglnewbee@163.com
