### ISSUE TITLE
return not reachable status when connect through shadowsocks

### ISSUE THREAD

**Issue by tomisacat** [dustturtle/RealReachability#16]
I use Surge with shadowsocks protocol to proxy my network connection and it always tells network not reachable when Surge is ON while reachable when Surge is OFF.

**Comment by dustturtle** [comment]
开启 shadowsocks 就会无法 ping。只代理 TCP 和 UDP。该代理不支持ICMP

**Comment by dustturtle** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/142
