### ISSUE TITLE
可不可以增加对多个Host的检测啊

### ISSUE THREAD

**Issue by hasayakey** [dustturtle/RealReachability#20]
因为app里有三个Host地址想检测啊。但目前好像就只支持一个吧

**Comment by zwy2937** [comment]
@dustturtle @maocl023 @pra85

**Comment by dustturtle** [comment]
目前支持1个，你想同时对多个host进行检测么？ 分别检测不同host的可达性？

**Comment by zwy2937** [comment]
对啊。但是你目前不都是一个单例啊，我想要分别知道每个host的可达性

**Comment by zwy2937** [comment]
@dustturtle

**Comment by zwy2937** [comment]
而且在切换网络的情况下。能不能回调出来前一个网络状态，省的我自己再去额外记录前一个网络是什么

**Comment by zwy2937** [comment]
希望能加上这两个功能

**Comment by dustturtle** [comment]
对于多host:你这个需求很奇怪。网络连接状态不应该需要知道几个host的可达性啊？host只是用来测试的工具而已。
对于之前的网络状态：你需要知道之前的网络状态的需求出发点什么？

**Comment by zwy2937** [comment]
因为我做的是视频直播的软件，我想知道对方服务器的可达性和我自己这边服务器的可达性。对于切换网络状态，是因为视频直播需要针对网络切换做出不同的调整，所以我得知道前一个网络状态是啥

**Comment by dustturtle** [comment]
视频直播本身就是建立连接的吧我理解，连接出问题应该有异常流程处理？
单独检测你可以使用pingFoundation基础类去ping。
2. 之前的网络状态我考虑单独增加一个接口/属性来返回。

**Comment by zwy2937** [comment]
我可以直接用pingFoundation检测啊。。好的好的

**Comment by zwy2937** [comment]
快点考虑加上吧

**Comment by dustturtle** [comment]
previousReachabilityStatus返回了该状态，具体请参考demo. @zwy2937

**Comment by dustturtle** [comment]
master上的最新版本引入了double check机制，可以设置两个ping地址，通过双地址+重试来保证可靠性，欢迎体验，谢谢～
