### ISSUE TITLE
网络监测情况不是很准

### ISSUE THREAD

**Issue by lhp3851** [dustturtle/RealReachability#22]
1.我在正常WiFi和3G之间切换还算正常，当我通过代理链接的时候，网络的实时监测情况就不准，有两种情况：
a.我代理填了一个假的代理（连接了WiFi但不能上网的情况）之后再切换真的代理（连接了WiFi且能上网的情况），就会经常出错,返回的链接基本上都是WiFi链接正常；
b.我代理填了一个假的代理（连接了WiFi但不能上网的情况）之后再切换真的代理（连接了WiFi且能上网的情况），然后在真代理和3G之间切换，基本上也会经常出错；

**Comment by dustturtle** [comment]
代理不支持ICMP包（ping包基于ICMP）的透传，因此才会出现这种情况。请参考https://github.com/dustturtle/RealReachability/issues/16 https://github.com/dustturtle/RealReachability/issues/17
此种情况需要开发者自行寻找解决方案或设计纠错策略

**Comment by lhp3851** [comment]
情况b:其实我在监测3G网的时候也会返回网络不可达。

**Comment by lhp3851** [comment]
![img_1970](https://cloud.githubusercontent.com/assets/5572476/13899199/05801be8-ee23-11e5-8b7b-b5f37013105c.PNG)
如此

**Comment by dustturtle** [comment]
3g时候是有时候会出现这种情况的.不过一会会恢复.因为此时网络质量不佳，ping有不小的概率失败；此处需要优化
