### ISSUE TITLE
切换网络到手机热点，没接收到网络变化通知？

### ISSUE THREAD

**Issue by xingye** [dustturtle/RealReachability#23]
为什么切换网络到手机热点，没接收到网络变化通知？

**Comment by dustturtle** [comment]
这里只通知网络连接类型的变化。如果之前连接的就是wifi网络，那么不会通知

**Comment by dustturtle** [comment]
wifi->wifi 不会通知，3g->4g的切换也不会通知

**Comment by xingye** [comment]
好奇怪，我上周使用localConnection的时候，wifi->wifi会收到通知的。

**Comment by dustturtle** [comment]
localConnection是可以通知的，这一层的变化被FSM(有限状态机)屏蔽了。这里的设计思路就是只通知网络连接性的变化，而不关心类似wifi->wifi, 3g->4g的变化

**Comment by xingye** [comment]
对不起，我一开始没描述清楚。
现在的问题是localConnection在从一个wifi切换到另一个wifi或者手机热点时也收不到通知了。

**Comment by dustturtle** [comment]
你单独使用了localConnection? 你对比Reachability或者afnetworking那个看看呢？ 这一块大家都大同小异的，没有本质区别啊，按照道理不会出现这种问题，再仔细检查检查通知的情况呢

**Comment by xingye** [comment]
试了Reachability和AF，在wifi之间切换都接收不到通知，不知道是不是跟网络环境有关？

**Comment by dustturtle** [comment]
有可能，反正不是代码层面的问题
