### ISSUE TITLE
在WiFi情况下,网络波动,从网络不可达到有网络状态回调很慢

### ISSUE THREAD

**Issue by BossKing** [dustturtle/RealReachability#24]
网络波动(并非切换网络方式),出现网络不可达,但是这是这一点不可达,未来的非常快的一个时间点恢复网络了,触发通知回调很慢(对于这一点的验证:我在网络不可达以后立马通过提供的block获取但网络状态是可达的)
代码如下:
#import "RRController.h"
#import "RealReachability.h"

@interface RRController ()

@property (weak, nonatomic) IBOutlet UILabel *statusLabel; /**< 网络状态视图 */

- (IBAction)clickBntForRR:(id)sender;

@end

@implementation RRController
#pragma mark - life cycle
- (void)viewDidLoad
{
    [super viewDidLoad];
    
    [self setupUIForRR];
}

- (void)viewWillAppear:(BOOL)animated
{
    [self refreshNetworkStatus];
}

- (void)dealloc
{
    BKLog(@"");
    
    [[NSNotificationCenter defaultCenter] removeObserver:self];
}

#pragma mark - event response
- (IBAction)clickBntForRR:(id)sender
{
    UIStoryboard *main = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
    UIViewController *detailController = [main instantiateViewControllerWithIdentifier:@"RRDetailController"];
    
    if (detailController)
    {
        [self.navigationController pushViewController:detailController animated:YES];
    }
}

#pragma mark - callback
- (void)applicationDidBecomeActive
{
    [self refreshNetworkStatus];
}

- (void)networkChanged:(NSNotification *)notification
{
    RealReachability *reachability = (RealReachability *)notification.object;
    ReachabilityStatus status = [reachability currentReachabilityStatus];
    
    BKLog(@"status = %zd", status);
    
    [self refreshStatusLabel:status];
}

#pragma mark - private method
- (void)setupUIForRR
{
    // notifications
    // 监听网络状态
    NSNotificationCenter *defaultCenter = [NSNotificationCenter defaultCenter];
    [defaultCenter addObserver:self
                      selector:@selector(networkChanged:)
                          name:kRealReachabilityChangedNotification
                        object:nil];
    // 监听程序获取焦点
    [defaultCenter addObserver:self
                      selector:@selector(applicationDidBecomeActive)
                          name:UIApplicationDidBecomeActiveNotification
                        object:nil];
}

- (void)refreshNetworkStatus
{
    [[RealReachability sharedInstance] reachabilityWithBlock:^(ReachabilityStatus status) {
        BKLog(@"status = %zd", status);
        
        [self refreshStatusLabel:status];
    }];
}

- (void)refreshStatusLabel:(ReachabilityStatus)status
{
    switch (status) {
        case RealStatusNotReachable:
        {
            [_statusLabel setBackgroundColor:[UIColor yellowColor]];
            [_statusLabel setText:@"无网络!"];
            break;
        }
        case RealStatusViaWWAN:
        {
            [_statusLabel setBackgroundColor:[UIColor greenColor]];
            [_statusLabel setText:@"手机网络!"];
            break;
        }
        case RealStatusViaWiFi:
        {
            [_statusLabel setBackgroundColor:[UIColor greenColor]];
            [_statusLabel setText:@"WiFi网络!"];
            break;
        }
        default:
            break;
    }
}

@end
![image](https://cloud.githubusercontent.com/assets/8686169/13975011/149a2490-f0ec-11e5-80a4-b786e8b1e346.png)

**Comment by BossKing** [comment]
本来我为演示效果录的是gif动画,不知为何显示成静态图片了...如果需要查看,QQ:983563622,谢谢!

**Comment by dustturtle** [comment]
applicationDidBecomeActive 里不需要手动调用reachabilityWithBlock，框架里已经做了处理。我加你qq了，细聊哈
