### ISSUE TITLE
网络侦测不正常

### ISSUE THREAD

**Issue by jinjuezhou** [dustturtle/RealReachability#26]
1:延迟问题，我在didFinishLaunchingWithOptions [GLobalRealReachability startNotifier] 进入app没有及时获取网络信息(wifi环境)

2:网络明明正常链接 过了一会儿又变成RealStatusNotReachable

**Comment by dustturtle** [comment]
1.进入app没有及时获取网络信息(wifi环境) 这个应该是你用法不对，请参考demo（初始化时不会发change的通知，而需要调用currentReachabilityStatus来获取）.
2. 变化是因为ping失败，说明网络连接不稳定。

**Comment by dustturtle** [comment]
1.进入app没有及时获取网络信息(wifi环境) 这个应该是你用法不对，请参考demo（初始化时不会发change的通知，而需要调用currentReachabilityStatus来获取）.
2. 变化是因为ping失败，说明网络连接不稳定。

**Comment by dustturtle** [comment]
1.进入app没有及时获取网络信息(wifi环境) 这个应该是你用法不对，请参考demo（初始化时不会发change的通知，而需要调用currentReachabilityStatus来获取）.
2. 变化是因为ping失败，说明网络连接不稳定。

**Comment by jinjuezhou** [comment]
就是demo用法。 我一直返回 RRStateLoading

**Comment by dustturtle** [comment]
是最新版本的么？ 方便的话可以发你的demo到我邮箱 openglnewbee@163.com，我给你看一下

**Comment by jinjuezhou** [comment]
好像是我们公司网络问题,已经解决 thanks
