### ISSUE TITLE
autoCheckInterval设置为CGFloat_Max时，在iOS9以下会不停地ping

### ISSUE THREAD

**Issue by suruihai** [dustturtle/RealReachability#29]
GLobalRealReachability.autoCheckInterval = CGFLOAT_MAX;
如题。

**Comment by dustturtle** [comment]
为何要设置成这个值？一般来说请参考建议值设置（比如2.0）。设置成这个值可能触发了bug？iOS9没问题？你的需求是什么

**Comment by suruihai** [comment]
是这样的，我的需求是我不希望autoCheck，而我没有发现能关闭autoCheck的属性，所以把这个interval设为了一个最大值。在iOS9以下，CGFLOAT_MAX ＊ 60 应该是归零了，此时会不停地ping

**Comment by suruihai** [comment]
幸亏在发布新版本前发现了，现在已经去掉了，要不然就悲剧了

**Comment by dustturtle** [comment]
抱歉了！您如果没有实时检测的需求，可以选用afnetworking的那个reachabilitymanager；因为这里如果没有autocheck效果就大打折扣了。这里check的流量消耗非常小的

**Comment by suruihai** [comment]
不不，我是有实际网络检测的需求的，您的框架使用非常方便，也很好地解决了我的问题，我现在把autocheck在startNotifier中的调用注释掉了，对于实际网络的变化还是能实时检测到的，这正是我需要的，也没有任何问题。建议给self.autoCheckInterval*60 的值加上一个非0判断，或者给一个建议的取值区间，不管怎么说，这个值在实际应用中是不能设为0的，这样也就避免出现不断地autocheck的情况。

**Comment by dustturtle** [comment]
已经在代码里面作了保护，现在范围在0.3f-60.0f之间（单位为分钟），代码已提交至master，请更新验证~ 谢谢您的反馈和支持！ @suruihai
