### ISSUE TITLE
PingHelper问题

### ISSUE THREAD

**Issue by dsmo** [dustturtle/RealReachability#30]
在 `pingWithBlock:(void (^)(BOOL isSuccess))completion`方法的`completion`中调用`pingWithBlock:`，第二次的block参数会在pingTimeOut之前被 ` [self.completionBlocks removeAllObjects]` 删除，导致第二个completion不能被调用。

**Comment by dustturtle** [comment]
这里不应该出现嵌套的调用，设计时用来单次触发的。快速多次调用也会被归并在一处返回，实际上不会ping多次。因为有自动周期check的机制，所以不需要手动的循环调用，请知
