### ISSUE TITLE
检测不了的网络多次关闭和打开

### ISSUE THREAD

**Issue by huangping35** [dustturtle/RealReachability#31]
RealReachability *t=[[RealReachability alloc]init];
    t.hostForPing=@"www.baidu.com";
    [t startNotifier];
    [t reachabilityWithBlock:^(ReachabilityStatus status) {
        
        NSLog(@"status %ld",status);
    }];

我利用上述代码，然后不停打开或者关闭网络，都没有打印出网络状态，这个如何解决？

**Comment by dustturtle** [comment]
这个block不是这样用的，他是触发式，一次性的，你这种场景可以不调用它。你只需要监听那个通知，然后开启startnotify就可以。请参考我的demo
