### ISSUE TITLE
请问此类库是否能在纯IPV6模式下正常运行

### ISSUE THREAD

**Issue by zxwcool** [dustturtle/RealReachability#33]
针对苹果iOS最新审核要求为应用兼容IPv6

**Comment by dustturtle** [comment]
有几处地方需要修改，计划在5月22日前修改并测试完成。

**Comment by zxwcool** [comment]
期待更新，正在使用！

**Comment by kkkelicheng** [comment]
关注中，谢谢作者。

**Comment by ylquankai** [comment]
请问作者，需要修改哪几个地方啊？tonymillion/Reachability 是否也能够做出相应的修改，从而支持iPv6-only网络

**Comment by dustturtle** [comment]
修改好了我会发上来。那个也可以的

**Comment by ylquankai** [comment]
能否简单说一下修改方案

**Comment by dustturtle** [comment]
reachability改起来应该要比我这个简单些。你可以参考：https://github.com/AFNetworking/AFNetworking/pull/3174/files。 http://www.jianshu.com/p/69ed4489762c 这篇博文也不错，还有就是多看看苹果官方文档。

**Comment by ylquankai** [comment]
看过AFN的解决方案：

#if (defined(__IPHONE_OS_VERSION_MIN_REQUIRED) && __IPHONE_OS_VERSION_MIN_REQUIRED >= 90000) || (defined(__MAC_OS_X_VERSION_MIN_REQUIRED) && __MAC_OS_X_VERSION_MIN_REQUIRED >= 101100)
    struct sockaddr_in6 address;
    bzero(&address, sizeof(address));
    address.sin6_len = sizeof(address);
    address.sin6_family = AF_INET6;
#else
    struct sockaddr_in address;
    bzero(&address, sizeof(address));
    address.sin_len = sizeof(address);
    address.sin_family = AF_INET;
#endif

感觉这样并不能解决问题，如果一个应用是从iOS9以下开始支持的，那还是会走else里的代码。这样在IPv6的网络下还是有问题的吧？

**Comment by dustturtle** [comment]
https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1
其他的只能等我做完再回答你了。 @ylquankai

**Comment by ylquankai** [comment]
好吧 多谢了

**Comment by dustturtle** [comment]
刚弄了个nat64的环境用iOS9设备试了下，reachability的话直接用afnetworking那种修改方式应该就可以，我试了我的localconnection修改后可以正常获取状态。至于为何他要用那个宏控制，我看了他的issue，好像是说iOS8下面哪儿有问题，才改的。你可以去他的issue里面讨论。深入研究的话还是多看看苹果文档。 @ylquankai

**Comment by dustturtle** [comment]
Support IPV6 now in master. Please try.  Found any issue around IPV6, contact me. Thank you! @zxwcool @kkkelicheng @ylquankai @pra85 @maocl023

**Comment by dustturtle** [comment]
pod1.1.5，ipv6 supported

**Comment by cctao** [comment]
可是为在ipv6 网络下， ios9.2 下运行也走的else 语句，问下啥情况走if 就是那个ipv6的选项

**Comment by ylquankai** [comment]
把项目的Development Target 改到9.0以上

**Comment by dustturtle** [comment]
那个其实并没有影响，不需要像afnetworking那样做。可以参考苹果的reachability最新版本里面的说明
