### ISSUE TITLE
希望作者可以开发swift版本～

### ISSUE THREAD

**Issue by pangpingfei** [dustturtle/RealReachability#35]

**Comment by buoge** [comment]
苹果Reachability已经可以直接检测设备联网状态，不在仅仅检测本地联网状态：
https://developer.apple.com/library/ios/samplecode/Reachability/Introduction/Intro.html

**Comment by buoge** [comment]
swift 用 桥接方式调用没啥区别，苹果官方也只给出oc 版没有 swift 版

**Comment by dustturtle** [comment]
@buoge 你这里的理解是有问题的。单单依靠reachability不能够解决所有问题。实际上我这里的localconnection模块和苹果的reachability没有本质区别。有兴趣可以看看源代码。

**Comment by dustturtle** [comment]
#25
