### ISSUE TITLE
你好，我想问一下 这个类库是否兼容IPv6

### ISSUE THREAD

**Issue by zhanwufeng** [dustturtle/RealReachability#36]
我现在项目中官方的那个网络监控  是3.5版的，不兼容IPv6，也没在官网找到最新版本的下载地址，直搜索到你上传到GitHub上这个版本，看时间时最新的，而且还是你封装好的，所有想知道是否支持，项目中其他的兼容设置我都已经改好了。6月份还有新版本上传app store，望看到后回复，谢谢！～

**Comment by dustturtle** [comment]
有几处地方需要修改的，计划大概在22号前后修改完，请知。请关注更新情况（follow我也可）

**Comment by zhanwufeng** [comment]
好的 谢谢
