### ISSUE TITLE
网络状态监听RealStatusViaWiFi，但实际不能上网。

### ISSUE THREAD

**Issue by changpk** [dustturtle/RealReachability#38]
手机连接了imac的wifi热点，imac运行了Charles，手机把Charles设置为代理，手机端要设置服务器ip地址和端口，故意写错了服务器IP地址（模拟能链接wifi，但上不了外网的情形），手机safari是打不开网页的，Demo检测网络状态依然为wifi状态，用PingHelper 直接去ping www.baidu.com也显示成功；这种情形能有效监测到吗？

**Comment by dustturtle** [comment]
charles只代理了http的请求，可能ping没有走那个代理，这个场景不在这个库的范围内哈。请知

**Comment by dustturtle** [comment]
ping检测是基于icmp协议的

**Comment by changpk** [comment]
谢谢，Chares代理了http，但ping是基于icmp协议的，所以可以ping通，但是手机是打不开web页面的！学习了！
