### ISSUE TITLE
从wifi切换到4G状态不对

### ISSUE THREAD

**Issue by changpk** [dustturtle/RealReachability#39]
运行demo，系统是9.3.1的iphone6，从底部拉出系统菜单，关闭wifi按钮，从wifi切换到4g，会出现提示RealReachabilityStatus4G，接着再次提示为Network unreachable！从底部拉出系统菜单，打开wifi按钮，从4G切换到wifi也会出现Network wifi! Free，再次提示为Network unreachable！原因是第一次正常，第二次就都是notreachable，反复较快切换，这种情况出现的频率较为高；尤其是从wifi切换到4g，状态出现错误的概率很大（现象同前面描述）；

**Comment by dustturtle** [comment]
你可以调试看下是不是ping timeout了。很可能是因为手机此时的移动网络不稳定造成的。过一段时间（2min左右）应该会自动恢复

**Comment by changpk** [comment]
调试过程中发现，中间通过FSM切换的时候，会出现这个判断！您这样操作，出现这种类似的情况没，就是再wif和4g之间切换的频繁下，因为一般这种提示是有个toast来告知用户，用户会觉得提示与当前网络状态不匹配！难道只能缩短ping的间隔来优化吗

**Comment by dustturtle** [comment]
如果是采用这种toast的方式，那我建议不要使用ping了。直接检测本地连接(local connection的检测可以单独使用)就可以了，否则确实不友好。

**Comment by changpk** [comment]
我想用这个库就是为了解决连接上 wifi，但实际 wifi 没有连接英特网的情形！所以这种状态的问题，在 wifi 到4g 之间切换，4g 稳定后是会出现这种unreach 的链接状态，通过代码优化能否达到？是否是因为多个状态之间转换出现的问题！

**Comment by dustturtle** [comment]
不是多个状态之间转换出现的问题，而是ping操作实际的失败导致的

**Comment by changpk** [comment]
ping操作实际的失败导致的，这是指在 wifi 和4g 之间切换，ping 很容易为失败吗？稳定之后，多次获取当前状态也为 unreach，感觉及时性有点滞后！

**Comment by dustturtle** [comment]
这个和你切换后的网络状态有关的，丢包率比较高的情况下，容易失败

**Comment by changpk** [comment]
从 wife 切换到4g，然后读取  ReachabilityStatus status = [reachability currentReachabilityStatus];发现总是 unreach！从 wifi 切换到4g却会很快就正常状态！难道在4g 情况下，ping 很容易失败或者超时吗？

**Comment by dustturtle** [comment]
这个来回切换的场景出现这种情况的几率确实比较高，有优化空间。wifi网络的质量一般来说确实要好于移动网络。谢谢您的反馈和建议！

**Comment by dustturtle** [comment]
我刚才试了一下，4g下访问www.baidu.com非常慢！你试下切换成www.qq.com域名看看是不是就ok了

**Comment by dustturtle** [comment]
@changpk

**Comment by changpk** [comment]
刚实验了下，还是有问题！
typedef enum
{
    RRStateInvalid = -1,
    RRStateUnloaded = 0,
    RRStateLoading,
    RRStateUnReachable,
    RRStateWIFI,
    RRStateWWAN
}RRStateID;
_allStates = @[[ReachStateUnloaded state], [ReachStateUnReachable state], [ReachStateLoading state], [ReachStateWIFI state], [ReachStateWWAN state]];数组里面和上面的应该需要对应吧！在FSMEngine.m中 FSMEengine init 的方法中！

**Comment by dustturtle** [comment]
是对应的啊。你加我qq 123016764

**Comment by dustturtle** [comment]
已作优化，请使用master版本测试，谢谢！

**Comment by wLeiX** [comment]
刚下了最新版本也是这种情况，从wifi切换到3g会收到两次通知，第一次是正确的，第二次就是没有连接。。

**Comment by dustturtle** [comment]
如果数据网络连接不够稳定是可能会出现ping失败的情况，理论上过一会应该能够恢复。 如果只需要检测本地网络可以只使用LocalConnection模块： pod 'RealReachability/Connection'
