### ISSUE TITLE
发现一个重复发送通知问题

### ISSUE THREAD

**Issue by wanghongbo** [dustturtle/RealReachability#40]
你好，感谢提供这么优秀的开源代码。在使用过程中，我发现在切换网络的时候有时（概率并不高）会接收到两次通知，而且第二次通知事件中获取到的网络连接状态是错误的。这种情况只出现在由无网络切换到有网络的时候，也就是说，从无网络切换到有网络时，先收到了一个网络变化通知，在这个通知事件中获取到的网络状态是“连接状态”，然后又收到了另一个网络变化通知，在这个通知事件中获取到的网络状态是“不可连接状态”，这会导致程序出现异常。我跟了下代码，发现用户在收起系统快捷操作面板（就是从屏幕底部滑出的那个面板）的时候会触发reachabilityWithBlock事件，在localConnectionChanged事件后面也有触发reachabilityWithBlock事件，有可能是reachabilityWithBlock中发出了重复的通知。不知道这是不是一个bug，还是我使用的方法有问题。

**Comment by dustturtle** [comment]
你好，请问下你用的是当前master的最新版本吗？如果不是，请尝试下载最新版本试一下，谢谢。最近针对此问题做了优化

**Comment by dustturtle** [comment]
如果在最新版本上遇到了这个问题，加我qq 123016764，我需要详细了解下，谢谢

**Comment by dustturtle** [comment]
@wanghongbo

**Comment by wanghongbo** [comment]
不客气～上个版本有这个问题，这个版本我今天刚集成，还需测试下，如果有问题我再反馈。

**Comment by luowenxing** [comment]
重复推送的问题发生在，通过上拉控制栏改变网络状态再下拉返回app的时候，`appBecomeActive`调用了`reachabilityWithBlock`，之后网络状态改变`localConnectionChanged`也调用了`reachabilityWithBlock `，这两个有先后顺序，但是`reachabilityWithBlock`里面`[GPingHelper pingWithBlock]`方法执行block的顺序不一定，所以通知发送的顺序也不一定，这就会导致程序异常，可能后接受到`appBecomeActive`发送的通知，网络状态是不正确的。我试了一下，当注释`appBecomeActive`的方法，不会出现异常。

**Comment by dustturtle** [comment]
楼上的试下最新版本呢。 有先后顺序调用block，后来者并不会触发ping操作的，只会在一次ping操作的结果中返回。理论上重复调用是不应该引起状态异常的 @luowenxing

**Comment by luowenxing** [comment]
我试的是最新版本的，依然有问题。结果就是导致当前网络状态是已连接，但是返回的是`NotReachable`

**Comment by dustturtle** [comment]
不会啊，我这里按照你的步骤反复操作都没问题。可以加我qq具体沟通下
