### ISSUE TITLE
通过代理链接的时候，网络的实时监测情况就不准，苹果官方最新版的Reachability已经解决真实联网状态的问题

### ISSUE THREAD

**Issue by buoge** [dustturtle/RealReachability#43]
苹果官方Reachability已经可以直接检测设备联网状态，不在仅仅检测本地联网状态：
https://developer.apple.com/library/ios/samplecode/Reachability/Introduction/Intro.html

而且开代理时检测也可以正常的返回联网状态

**Comment by dustturtle** [comment]
Note: Reachability cannot tell your application if you can connect to a particular host, only that an interface is available that might allow a connection, and whether that interface is the WWAN. To understand when and how to use Reachability, read "Networking Overview" 建议好好理解下上面这段话，看下reachability的原理

**Comment by buoge** [comment]
好的，看到了，不好意思，我本地测试了下通过代理获取联网状态，官方那个可以，就急冲冲的提了个issue,没注意看Note不好意思浮躁了

**Comment by dustturtle** [comment]
感谢关注，我注意到你在另外一个issue（关于swift）里面的分享，非常有价值！谢谢您的贡献！
