### ISSUE TITLE
更新之后我这发现crash

### ISSUE THREAD

**Issue by JonnyFan** [dustturtle/RealReachability#44]
RealReachability的init方法里
_hostForPing = kDefaultHost;这样写，没走- (void)setHostForPing:(NSString *)hostForPing这个方法，导致GPingHelper.host设置不成功，会在
- (instancetype)initWithHostName:(NSString *)hostName {
    NSParameterAssert(hostName != nil);
    self = [super init];
    if (self != nil) {
        self->_hostName   = [hostName copy];
        self->_identifier = (uint16_t) arc4random();
    }
    return self;
}
这个方法里崩溃。
改为self.hostForPing = kDefaultHost;没问题

**Comment by dustturtle** [comment]
按照文档里说明的使用方法应该没有这个问题啊（参考demo）。能否把主要调用代码贴出来看看，接口的调用和顺序。如果有demo发我邮箱更佳，谢谢 openglnewbee@163.com @JonnyFan

**Comment by dustturtle** [comment]
请确认是否是在并未调用 [GLobalRealReachability startNotifier]的情况下调用了 [GLobalRealReachability reachabilityWithBlock:nil]的方法。 根据我的模拟测试，在此情况下会触发你描述的崩溃。 请注意：startNotifier才是开启监听的动作，reachabilityWithBlock需要在startNotifier之后被调用~ 如果按照你描述的那样修改，即使不崩溃，框架也无法正常运行。 谢谢！有问题请再联系我哈 @JonnyFan

**Comment by JonnyFan** [comment]
确实是你说的原因，我后调用了[GLobalRealReachability startNotifier]， 问题解决了，非常感谢！

**Comment by dustturtle** [comment]
不客气！感谢您的关注和反馈哈^_^～@JonnyFan
