### ISSUE TITLE
网络监控极度不稳定

### ISSUE THREAD

**Issue by jiangmingz** [dustturtle/RealReachability#45]
我们使用这个库监控网络状态后，用户大量反馈没有网络。但用户都是有网络的。要么是 wifi，要么是4G 状态下面的。造成用户不能使用其他功能了。

**Comment by dustturtle** [comment]
1.建议升级到最新版本（1.1.7）
2.建议不强制用户无法使用功能，而作一些用户友好的提示（网络状况不佳，可能无法使用服务，类似这样）；
3.如果1和2仍然不能满足您的需求，建议单独使用pod 'RealReachability/Connection'，只检测本地网络连接，不启用ping检测。

**Comment by jiangmingz** [comment]
我们播放率直接下降了10%

**Comment by dustturtle** [comment]
我的qq 123016764 ，需要进一步沟通可以加我，谢谢

**Comment by jiangmingz** [comment]
我试出来了一次就是本地网络变化是成功的，但是 ping 出问题了，返回的是无网络。
