### ISSUE TITLE
崩溃：0x0014d4fb -[PingFoundation startWithHostAddress] (PingFoundation.m:672)

### ISSUE THREAD

**Issue by ixiaogangwyg1** [dustturtle/RealReachability#46]
我使用非最新版本时，线上会有崩溃现象。
出错机型：iPhone4s、5、6、6plus。
系统：iOS8.x和iOS9.x，自己测试没有出现，线上用户使用出现崩溃。不知道最新版本是否修复？
崩溃日志如下：
<img width="840" alt="2016-07-11 8 35 35" src="https://cloud.githubusercontent.com/assets/3830067/16730809/8aba59f8-47a7-11e6-97e3-38668450e69e.png">
以上。谢谢！

**Comment by dustturtle** [comment]
这个是之前版本出现过的问题，已经修复了（closed issue里有人提过）。请使用最新版本！

**Comment by ixiaogangwyg1** [comment]
好的，谢谢！

**Comment by ixiaogangwyg1** [comment]
上面那个崩溃，我更新到了1.1.7版本，通过线上bug统计工具显示，这个问题还是存在。昨天app上线的，统计到了7次crash，影响7个用户。
崩溃日志信息和上面一样。

**Comment by dustturtle** [comment]
看你的日志信息是这里的代码assert失败了（创建runloopSource返回结果为空）
rls = CFSocketCreateRunLoopSource(NULL, self.socket, 0);
        assert(rls != NULL);
目前还不清楚触发的场景和原因 。不知道你这里的用法是怎样的，如果不需要ping功能，可以只使用pod 'RealReachability/Connection'。

**Comment by ixiaogangwyg1** [comment]
谢谢回复。 我的用法是获取用户当前使用的网络情况，例如是Wi-Fi、4G、3G。
另外我断点调试看了一下，获取网络状态方法之前，是开启了监测的。
 目前我们自己也没有测试重现这个问题。 只是从上个版本开始，出现了日志里的错误。不知道用什么方法去模拟重现这个问题。

**Comment by ixiaogangwyg1** [comment]
从日志分析里面看，用户使用的页面路径，是当用户切换到后台或者从后台切换到前台的时候出现崩溃。
机型以iPhone4s iOS9.x以上为主。 不知道这种情况下，会有什么原因导致崩溃呢？

**Comment by dustturtle** [comment]
可能是苹果的pingFoundation里面，在某些前后台切换场景下触发了assert；这块我之前改过（后来pingFoundation替换成苹果新版本的了），新版本以后没有再修改；过几天我好好梳理下（这几天有些忙，见谅） @ixiaogangwyg1

**Comment by ixiaogangwyg1** [comment]
嗯 好的，先谢谢你了～

**Comment by ixiaogangwyg1** [comment]
hi， 我看到最近2天有更新，这个更新修复了我提的那个bug吗？
如果没有修复的话，计划什么时候呢？谢谢～

**Comment by dustturtle** [comment]
这个更新和之前你提的bug无关的，计划本周内吧，修改了我会@你的，谢谢 @ixiaogangwyg1

**Comment by ixiaogangwyg1** [comment]
好的，等你通知，谢谢。

**Comment by dustturtle** [comment]
已经修改了你那个问题相关的代码，请更新，谢谢！ 如果有任何问题继续反馈给我哈 @ixiaogangwyg1

**Comment by ixiaogangwyg1** [comment]
好的，我更新一下，不过pods好像没有更新吧？

**Comment by dustturtle** [comment]
没有

**Comment by ixiaogangwyg1** [comment]
那什么时候更新呢？我是用pod管理的

**Comment by dustturtle** [comment]
稍微观察几天就更新。手动集成也很简单的 @ixiaogangwyg1

**Comment by ixiaogangwyg1** [comment]
好的 谢谢～

**Comment by ixiaogangwyg1** [comment]
请问有更新pod的时间表了吗？😄

**Comment by dustturtle** [comment]
本周内就会更新

**Comment by dustturtle** [comment]
已经更新了1.1.8 @ixiaogangwyg1

**Comment by dustturtle** [comment]
@ixiaogangwyg1 新版本情况如何啊

**Comment by ixiaogangwyg1** [comment]
不好意思，后来调整了app里面的用法，暂时没有使用了。
