### ISSUE TITLE
不知道是ios7还是因为手机是越狱的情况，判断不可用啊

### ISSUE THREAD

**Issue by wlerl** [dustturtle/RealReachability#47]
如题，就是我有个4s，越狱的，ios7，有做一些判断网络环境的操作，然后经常就是连着wifi，开始调试，点击，点击某个按钮进行网络请求，然后就判断成为了不是wifi个2 G 3 G 4G 的那个选项，另外2个就是一个没联网一个未知嘛。我这是连着公司wifi的，所以不知道是什么情况，求大神指教？（这个判断网不对我就只有重新commen+r）

**Comment by dustturtle** [comment]
这个是异步请求如果一直断点停住会超时的。如果单单使用localconnection检测应该就没有这种情况。调试的时候也可以先不判断网络

**Comment by wlerl** [comment]
没有断点，如果你说异步请求会断点超时的话那可能是因为是4S，内存不够用，所以处理app非常慢，然后就造成了超时，不过感觉应该不会是这个原因吧，因为我是点击一个按钮，然后在进行网络请求前我就会先判断网络状态，如果是网络状态不对的话就会弹框提示，就不会进行网络请求那边去

**Comment by dustturtle** [comment]
那你这个是必现的还是偶现的？ @wlerl

**Comment by wlerl** [comment]
偶现，因为这样的时候我就commend+ r，有的时候一次就可以了，有的时候要几次才会判断到正确的网络，当然，也只是在4上面，这个是越狱的，外加系统是Ios7，然后在别的手机上面，基本都是对的

**Comment by wlerl** [comment]
@dustturtle 关了4G的话，就会很容易判断成无网络，然后就一堆不可用，这个时候就只有切wifi或者重启app，这个情况今天出现的比较多的，不知道是不是楼主在判断状态那边做了缓存，然后直接拿的缓存的，然后这个判断网络状态就是实在不懂，因为这个手机上在这个wifi下是可以看别的app，所以网络肯定没问题，但是会出现判断网络失败，然后我很多操作都是没网络就不然进，但其实有网（感觉目前只能用来做提示不能用来做判断啊，实在不知道是什么情况）

**Comment by wlerl** [comment]
@dustturtle 楼主，最近网络状态判断有问题，目前只好弃用啊，经常会有判断不准啊，求更改啊

**Comment by dustturtle** [comment]
如果没有判断伪连接的需求可以直接检测本地网络连接状态，pod 'RealReachability/Connection'
或者使用其他类似的框架，比如afnetworking的网络检测，功能都差不多，接口稍有不同

**Comment by wlerl** [comment]
@dustturtle 那就没意义了，本来觉得楼主做的好就是因为楼主判断了伪连接，还是等待楼主能有时间将这个框架做的更好吧，期待楼主做的更好！

**Comment by dustturtle** [comment]
这个跟应用场合有关的，好比你很多时候网络慢，网页不容易刷出来，但多试几次还是可以。主要是有些路由器会禁ping这个比较烦
