### ISSUE TITLE
从无网络切换到WIFI时networkChanged方法的status等于NotReachable

### ISSUE THREAD

**Issue by coooliang** [dustturtle/RealReachability#5]
从无网络切换到WIFI时networkChanged方法的status等于NotReachable，可以来回切换测试一下哦

**Comment by dustturtle** [comment]
真机测试吗？无网络是什么情况（本地连接就没有，还是伪连接）？确定Wi-Fi可以上网吗？

**Comment by dustturtle** [comment]
我这里按照你的步骤反复测试是没有问题的，希望提供更多供分析的细节，谢谢！也可以debug看下日志

**Comment by dustturtle** [comment]
未收到反馈，暂时关闭该issue，请联系openglnewbee@163.com，谢谢
