### ISSUE TITLE
用block来实时监听网络状态，碰到网速慢的时候返回的状态为RealStatusNotReachable

### ISSUE THREAD

**Issue by GreatLiyi** [dustturtle/RealReachability#50]
求修改，这个很影响体验，网速慢的时候被认为断网了

**Comment by dustturtle** [comment]
这里的实现策略就是这样的，网速慢的时候ping失败，然后返回无法连接，只有等待下次检测。 我的初衷是可以友好的提示用户“当前网络较差”之类；如果不能满足要求，目前就不要使用ping的能力。
