### ISSUE TITLE
关于打印日志的问题

### ISSUE THREAD

**Issue by devcxm** [dustturtle/RealReachability#51]
个人觉得正常情况下打印日志是为了调试和查看错误状态信息，RealReachability库的使用者只关心库是否正常响应，虽然生产环境去除了日志，但是在开发环境，对于多余正常的日志信息我们也不关心，反而会影响我们查看其它错误日志信息，看到那么多无用的日志，真的很烦。所以我建议作者做2个调整：
1、添加宏定义并用累似RRLog来替换RealReachability中的NSLog
#ifdef DEBUG
#define RRLog(...) NSLog(__VA_ARGS__)
#else
#define  RRLog(...)
#endif
2、提供一个日志开关，用于控制打印日志（默认关掉）。

**Comment by dustturtle** [comment]
很多第三方库（比如fmdb）都不会单独去封装一个日志（这里我主要是为了方便），可能我这里有个别日志是在正常场景下输出的（通常是为了报告异常），所以给你带来了一些困扰；我个人开发项目使用基于cocoalumberjack定制的日志系统，这里我为了避免依赖和简单考虑，使用了上面的方法。
回复你的调整措施：
1.后面我考虑去掉个别打印频繁的正常日志
2.你也可以考虑fork一下对这块进行简单修改
PS:建议查找错误日志信息的时候尽量使用关键字进行过滤

**Comment by dustturtle** [comment]
@devcxm 我在最新提交里去除了异常以外的其他NSLog打印。 谢谢！ @devcxm
