### ISSUE TITLE
移除NSLog

### ISSUE THREAD

**Issue by levey** [dustturtle/RealReachability#52]
快要把Ping的log移掉吗，以一个第三方库来说，这种log算是侵入式的了。

**Comment by dustturtle** [comment]
@levey 已经移除异常外的其他NSLog打印 
PS:这里的日志打印仅在debug下才生效

**Comment by levey** [comment]
@dustturtle  记得更新 podspec 哦。

**Comment by dustturtle** [comment]
@levey 谢谢提醒哈，pod晚点再说咯 ^___^
