### ISSUE TITLE
iphone 5C 监听网络状态 返回的网络状态 

### ISSUE THREAD

**Issue by yuyangdexue** [dustturtle/RealReachability#56]
iphone 5C 监听网络状态 返回的网络状态  不对 总返回没有网络  而手机可以访问其他网络

**Comment by dustturtle** [comment]
连接vpn了吗？ 还是连的wifi不可以ping？ 这个理论上和手机型号无关

**Comment by yuyangdexue** [comment]
嗯 找到问题了  没有正确使用  谢谢了
