### ISSUE TITLE
可否增加对ip+port的检测支持？

### ISSUE THREAD

**Issue by kangle1208** [dustturtle/RealReachability#57]
你好
我在看了源码后，发现PingFoundation的start方法中
self.host是用CFHostCreateWithName方法生成的
我自己又加了用CFHostCreateWithAddress方法生成self.host
但是发现加了端口号以后，始终都是返回无连接状态
请问这个是为什么呢？

**Comment by dustturtle** [comment]
http请求是针对端口号，这里的ping的icmp协议是没有端口号的概念的。你的思路往下走可以尝试开发一个基于http请求的检测哈。

**Comment by kangle1208** [comment]
是哦，忘了，ping的时候带端口号始终是说unknow host～～日啊～～
