### ISSUE TITLE
用PING功能在 移动4G网络的情况下是PING不通的，不知道作者咋解决的？ 我自己下载的苹果PING DEMO,r然后用的SWIFT调用的。

### ISSUE THREAD

**Issue by hatjs880328** [dustturtle/RealReachability#58]
用PING功能在 移动4G网络的情况下是PING不通的，不知道作者咋解决的？ 我自己下载的苹果PING DEMO,r然后用的SWIFT调用的。

**Comment by dustturtle** [comment]
移动4g网络状况如何？一直显示ping不通吗？ 一般情况下4g也是可以ping通的,不存在ping不通的问题

**Comment by hatjs880328** [comment]
你们对移动4G 这个ping功能做过测试吗？

**Comment by dustturtle** [comment]
从未有人反馈过这个问题。移动4g的场景相当普遍。我自己用的是电信4g

**Comment by loveNoodles** [comment]
ping 不通啊 ping 不通

**Comment by jiangjunwy** [comment]
因为在移动4g下出现ping的问题，所以我失业了

**Comment by jiangjunwy** [comment]
因为在移动4g下出现ping不同的问题，所以我失业了
