### ISSUE TITLE
特殊网络状态下，ping问题。

### ISSUE THREAD

**Issue by CoderTaoX** [dustturtle/RealReachability#59]
由于工作上的原因，网络大都是内网或者内网挂VPN，使用的都是IP+端口号，在这种状态下，使用GLobalRealReachability.hostForPing，即使在有网的情况下（WIFI及4g），依旧提示没有网络连接，请问有什么解决方法？

**Comment by dustturtle** [comment]
vpn的情况当前方案无法有效检测，原因是其只代理了http，并未代理icmp，从而导致了ping失败
