### ISSUE TITLE
i have wifi but it is Network unreachable

### ISSUE THREAD

**Issue by RMKitty** [dustturtle/RealReachability#6]
i have wifi but it is Network unreachable.  it has wifi then change to Network unreachable

**Comment by dustturtle** [comment]
请提供更多细节.是否一直无法恢复呢？
看看能稳定复现吗,还是偶然的。 根据我实际应用中的经验，如果稳定复现需要确认下safari打开的是否是浏览器缓存； 如果偶现则是很可能因为网络很慢ping包无法在超时时间内返回导致的。 最晚2分钟以内应该就会恢复正常的状态值
请测试时间长一点看看。 也可以直接联系我 openglnewbee@163.com 谢谢

**Comment by dustturtle** [comment]
和楼主沟通后，决定关闭此issue. (偶现情况，可能和网络有关。已在规划一些策略去优化了，敬请期待)

**Comment by aptx5788** [comment]
是不是 iOS 8 的系统？
