### ISSUE TITLE
PingFoundation.h:Unknown type name 'sa_family_t'

### ISSUE THREAD

**Issue by zhangpqan** [dustturtle/RealReachability#62]
RealReachability/Ping/PingFoundation.h:113:41: Unknown type name 'sa_family_t'

**Comment by dustturtle** [comment]
是你工程的问题？这个是系统定义的，应该没有问题

**Comment by xff8175** [comment]
我也碰到这个问题了

**Comment by NSDeveloper** [comment]
`#include <sys/socket.h>`
