### ISSUE TITLE
Carthage支持的问题

### ISSUE THREAD

**Issue by NeverAgain11** [dustturtle/RealReachability#64]
通过Carthage build之后，生成的 framework 的 deploy target 是 iOS6，而iOS8之后才支持framework，上传到iTunes connect的时候会报错。
能否将Carthage支持的版本改为iOS8

**Comment by dustturtle** [comment]
你的app的deployment target选的是iOS8吗？

**Comment by NeverAgain11** [comment]
是的，Carthage最低就支持iOS 8，要使用Carthage就必须deployment target 在iOS 8之后。

**Comment by dustturtle** [comment]
你现在手动改没问题吧？

**Comment by NeverAgain11** [comment]
试过了，手动改的话，Carthage update 生成 framework 的时候，Carthage checkouts 文件夹下的 .xcodeproj 会变回原先设定的 deployment target.

**Comment by NeverAgain11** [comment]
然后就会提示：ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
上传到 iTunes connect 的时候就上传不了

**Comment by dustturtle** [comment]
Would you please try this again? I've modified the target to iOS 8 in the latest master version.

**Comment by dustturtle** [comment]
@NeverAgain11

**Comment by NeverAgain11** [comment]
$ carthage update --platform ios
*** Fetching RealReachability
*** Fetching SnapKit
*** Checking out RealReachability at "1.1.8"
*** Checking out SnapKit at "3.0.1"
*** xcodebuild output can be found in /var/folders/14/fx6_nkt9363dkcw145snrgcc0000gn/T/carthage-xcodebuild.xb2OnN.log
*** Building scheme "RealReachability" in RealReachability.xcodeproj
*** Building scheme "SnapKit" in SnapKit.xcworkspace
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later

还是有问题。

**Comment by dustturtle** [comment]
现在应该是 Checking out RealReachability at "1.1.8.1"

**Comment by NeverAgain11** [comment]
可以了，刚刚试了，上传成功了。
