### ISSUE TITLE
移动网络下监听的还是没有网络

### ISSUE THREAD

**Issue by liuyihsou** [dustturtle/RealReachability#65]
切换成移动网络,最后还是监听成没有网络

**Comment by dustturtle** [comment]
wifi下正常？是一直没有，还是一会有一会没有？ ping失败会认为状态异常，后续会自动恢复的

**Comment by liuyihsou** [comment]
大概需要1分多钟，会变成移动网络状态

**Comment by liuyihsou** [comment]
希望能在2--3秒就监听准确

**Comment by liuyihsou** [comment]
我直接用你的demo测试，也是这种情况

**Comment by dustturtle** [comment]
这个是跟你当前网络相关的，你这种情况可以考虑不使用ping，单独使用： pod 'RealReachability/Connection'

**Comment by liuyihsou** [comment]
但我还想准确的监听网络是否真正可以上网，因为我们这个项目主要是跟WiFi交互

**Comment by liuyihsou** [comment]
'RealReachability/Connection 这个可以准确检测网络是否真正可用吗？

**Comment by dustturtle** [comment]
这个只能检测本地网络连接情况，比如wifi连接是否正常，wifi是否能上网无法保证。
ping失败的阈值你可以调整一下适应你的需求。

**Comment by liuyihsou** [comment]
好的，多谢
