### ISSUE TITLE
检测出现问题

### ISSUE THREAD

**Issue by coolboy-ccp** [dustturtle/RealReachability#66]
`我的手机已经连接网络，可以正常上网，但是返回的状态为不能上网RealStatusNotReachable，求解。``- (IBAction)searchNet:(UIButton *)sender {
    [GLobalRealReachability startNotifier];
    [GLobalRealReachability reachabilityWithBlock:^(ReachabilityStatus status) {
        [self refreshNetViewWithStatus:status];
    }];
    [[[NSNotificationCenter defaultCenter] rac_addObserverForName: kRealReachabilityChangedNotification object:nil]subscribeNext:^(NSNotification *x) {
        RealReachability *bty = (RealReachability *)x.object;
        ReachabilityStatus status = [bty currentReachabilityStatus];
        [self refreshNetViewWithStatus:status];
    }];
}

- (void)refreshNetViewWithStatus:(ReachabilityStatus)status {
        if (status == RealStatusViaWiFi) {
            self.netV.color = RGBA(100, 220, 220, 1.0);
            [self.netV setNeedsDisplay];
        }
        else {
            self.netV.color = RGBA(220, 220, 220, 1.0);
            [self.netV setNeedsDisplay];
        }`
断点po了一下status为RealStatusNotReachable；

**Comment by dustturtle** [comment]
你这个用法不太对，动作方法里面不应该有其他东西，最多就是触发一次ping或者查询当前状态。参考demo改下再试试。不用重复start和监听的

**Comment by coolboy-ccp** [comment]
首先谢谢回复！没有啊，我之前在公司检测都是好的。而且我现在检测已经好了，我这个事件在其他地方做了处理只能触发一次。我这边的网络应该比较稳定，可以看视频的。
不知道是不是偶尔丢包引起的，也可能是我手机原因吧！






在2016年09月26日 22:49，Achen 写道:

你这个用法不太对，动作方法里面不应该有其他东西，最多就是触发一次ping或者查询当前状态。参考demo改下再试试。不用重复start和监听的

**Comment by coolboy-ccp** [comment]
发自网易邮箱大师
在2016年09月26日 22:49，Achen 写道:

你这个用法不太对，动作方法里面不应该有其他东西，最多就是触发一次ping或者查询当前状态。参考demo改下再试试。不用重复start和监听的

**Comment by dustturtle** [comment]
那应该是偶现的ping失败，会自动恢复的
