### ISSUE TITLE
Benefits over current approach

### ISSUE THREAD

**Issue by thiagoperes** [dustturtle/RealReachability#7]
Hey,

Just out of curiosity, what are the benefits of using this over Reachability or SCNetworkReachability.

My impression is that this would allow for faster feedbacks into the connection status by using pinging, is that it?

Thanks!

**Comment by dustturtle** [comment]
ping is introduced to handle the situations below (I called that fake connection):
1. wifi network needed to be verify in the portal, if not , the connection is useless
2. signal too weak for your request
3. wifi router maybe no lan connect 
Another optimization is FSM, that make sure state change is really change, can not be 1 to 1.
