### ISSUE TITLE
网络切换的时候变成无网络的问题

### ISSUE THREAD

**Issue by pspzx** [dustturtle/RealReachability#70]
当我的网络是3G的时候，我打开WIFI以后，文本的变化是3G，然后到WIFI，一瞬间就变成了unreachable，在下次检测之前一直都是unreachable的状态。反过来也是一样，比如我是WIFI网络，我把系统的WIFI开关关闭,文本变化是WIFI到3G然后突然变成unreachable一直持续到下次自动检测的时候，这如何解决？

**Comment by pspzx** [comment]
我用的是最新master版本的

**Comment by dustturtle** [comment]
这种情况一般就是偶现的ping失败，你可以考虑尝试缩短自动检测的周期。

**Comment by dustturtle** [comment]
这种情况一般就是偶现的ping失败，你可以考虑尝试缩短自动检测的周期。
