### ISSUE TITLE
可否设置ping的次数，假若ping的次数可以自定义，就不会那么频繁的回调了

### ISSUE THREAD

**Issue by nizenyang** [dustturtle/RealReachability#71]
因为现在是切换网络的时候，一下有，一下没有的，可否给个缓冲的时间，比如设置ping的数次或者设置失败后，在短暂的几毫秒之内又重新连接上了，那么久可以忽略那么时间的链接失败的情况，这样可能用户体验上来说会更好一点

**Comment by dustturtle** [comment]
master上的最新版本引入了double check机制，可以设置两个ping地址，通过双地址+重试来保证可靠性，欢迎体验，谢谢～

**Comment by dustturtle** [comment]
同时会避免频繁的状态跳变
