### ISSUE TITLE
有些无线网络是禁ping的怎么办 360随身wifi就不能ping任何地址

### ISSUE THREAD

**Issue by wengold001** [dustturtle/RealReachability#72]
我们使用的时候，连接360随身wifi，网络是可以访问的，但是wifi不能ping通任何地址。网络监测就成了没有wifi了。这种情况应该怎么办。

**Comment by dustturtle** [comment]
wifi路由都有禁用和启用ping的选项吧？目前没有什么好的办法，只能友好提示了

**Comment by lianleven** [comment]
@wengold001 这种情况下建议在封装一层，如果没有网络的情况下，自己请求一下自己的服务器。
