### ISSUE TITLE
PingHelper类下的pingWithBlock:有内存泄漏

### ISSUE THREAD

**Issue by zhfei** [dustturtle/RealReachability#73]
- (void)pingWithBlock:(void (^)(BOOL isSuccess))completion
{
    //NSLog(@"pingWithBlock");
    if (completion)
    {
        // copy the block, then added to the blocks array.
        @synchronized(self)
        {
            [self.completionBlocks addObject:[completion copy]];
        }
    }
    
    if (!self.isPinging)
    {
        // MUST make sure pingFoundation in mainThread
        __weak __typeof(self)weakSelf = self;
        if (![[NSThread currentThread] isMainThread]) {
            dispatch_sync(dispatch_get_main_queue(), ^{
                __strong __typeof(weakSelf)strongSelf = weakSelf;
                [strongSelf startPing];
            });
        }
        else
        {
            [self startPing];
        }
    }
}
该方法中  [strongSelf startPing]; 这句出现内存泄漏

**Comment by dustturtle** [comment]
是 instruments 检测的还是其他工具报的啊？

**Comment by dustturtle** [comment]
xcode 8 下 真机跑 instruments 无泄露；请检查是否是你调用的代码造成的
