### ISSUE TITLE
在使用VPN的情况下ping的处理问题

### ISSUE THREAD

**Issue by phpmaple** [dustturtle/RealReachability#74]
如果在使用一些 VPN 只代理 TCP UDP 的情况下，ping 走 ICMP 就会失效，可否在 ping 的时候有可选项或者在VPN的时候走 HTTP 去检测一下网络 虽然比 ICMP 消耗流量，至少可以判断正确，不然现在用户开 VPN 其实网络有效 但是在里面确实网络连接失败

**Comment by dustturtle** [comment]
目前没有发现有效的方法检测当前是否链接是否是vpn

**Comment by phpmaple** [comment]
@dustturtle  那可否一个不太好的解决方案是当 ICMP ping 超时之后尝试 HTTP 去检测一下呢，当然可以这个可以是一个可选项，至少 VPN 情况下检测有用，不知道可行否

**Comment by dustturtle** [comment]
理论上应该是可以的

**Comment by jackieyk** [comment]
同样遇到了这个问题，我现在处理的方式是，如果ICMP ping timeout了，马上发出一个httpPing（HEAD request）, 如果httpPing也timeout了，那就是真的timeout了。
网络流量到是没有多费多少，因为只有timeout时才这样处理。但的确会使检查效率变低，识别timeout的时间是以前的2倍，算是个笨方法。期望有更好的方法解决这个问题。

**Comment by dustturtle** [comment]
solved in the master version
