### ISSUE TITLE
在检测网络实时状态的时候发生未知错误

### ISSUE THREAD

**Issue by LvyLiu** [dustturtle/RealReachability#76]
这些是报错信息。
onEvent error:Error Domain=FSM Code=13 "未能完成操作。（“FSM”错误 13。）"
warning! reachState uncertain! state unmatched, treat as unreachable temporary
我想请问这个是我调用有问题，还是什么？
谢谢

**Comment by dustturtle** [comment]
这个应该是调用问题，一般不会出现的
