### ISSUE TITLE
wifi 和 4G 状态下从后台到前台出现 dnssd_clientstub deliver_request ERROR: write_all(5, 54 bytes) failed

### ISSUE THREAD

**Issue by aptx5788** [dustturtle/RealReachability#77]
wifi 和 4G 状态下从后台到前台出现 dnssd_clientstub deliver_request ERROR: write_all(5, 54 bytes) failed

**Comment by aptx5788** [comment]
dnssd_clientstub write_all(5) DEFUNCT
dnssd_clientstub deliver_request ERROR: write_all(5, 54 bytes) failed
dnssd_clientstub write_all(5) DEFUNCT

**Comment by dustturtle** [comment]
iOS10下很多类似的系统日志的，一般来说不影响业务可以忽略
