### ISSUE TITLE
iOS 8 系统网络监测不准确

### ISSUE THREAD

**Issue by aptx5788** [dustturtle/RealReachability#78]
iOS 8 系统网络监测不准确 
wifi 状态下 先检测到 wifi 然后又检测到 无网络

**Comment by jackywpy** [comment]
遇到同样的问题

**Comment by aptx5788** [comment]
已改用 YYRealReachability

**Comment by aptx5788** [comment]
已改用 YYReachability

**Comment by dustturtle** [comment]
应该是可以恢复的，ping是有概率失败的。你确定是iOS8问题？其他系统ok?  YYReachability就是本地网络(对应本库的localconnection模块)，如果你没有检测实际连接状态的需求，确实不需要使用realReachability

**Comment by aptx5788** [comment]
同一网络环境下 iOS 8 和 iOS 10 都试过， iOS 8 会出现这个问题， iOS 10 没有问题

**Comment by dustturtle** [comment]
等待一段时间是否可以恢复？

**Comment by aptx5788** [comment]
貌似不可以

**Comment by TangledHusky** [comment]
同样碰到此问题

不过我是10.2的系统，wifi下，先提示wifi，然后瞬间变为unreachable，而且一直不恢复。。。

不知道是不是因为bug导致

**Comment by LomyCool** [comment]
发现使用mac共享出来的wifi，有一定几率失败，先提示wifi，然后瞬间变为unreachable，而且不会恢复

**Comment by dustturtle** [comment]
可能原因是这种wifi下禁用了ping操作；但可以进行http请求

**Comment by MarkTangs** [comment]
有网络，可是过一会就会 报无网络，每次启动 必现，监听开始是不是不能再didFinishLaunchingWithOptions开启？

**Comment by liya0412** [comment]
一直在WiFi环境下，运行APP，偶尔会出现网络status == RealStatusNotReachable的状态，

**Comment by xdream86** [comment]
断网的时候会有回调，网络连通后却没有回调

**Comment by coderLCX** [comment]
我也遇到相同的问题，明明有网却提示我无网络连接，只有当我把app切出去，用Safari请求下网页，才会正常

**Comment by coderLCX** [comment]
我也遇到相同的问题，明明有网却提示我无网络连接，只有当我把app切出去，用Safari请求下网页，才会正常

**Comment by liya0412** [comment]
好吧，这个是bug，不过这个原理我也不懂，只是用用，希望作者能完善这个bug，不然我们也不敢用。谢谢作者！

**Comment by carusd** [comment]
默认重试时间是2分钟一次，如果一次ping不通，后面就会有2分钟的真空状态，我试试失败之后改成1秒重试，有效果我会回来告诉大家。

**Comment by lianleven** [comment]
这个大家替换掉ping地址，默认ping的是www.apple.com，这个地址很难打开，库里面的超时时间默认设置的是2s,导致ping的超时，所以没网络。

**Comment by xingfuqiu** [comment]
刚开始的时候一直显示 RealStatusNotReachable ,后来才发现是 Surge 的锅,关闭了就都正常了.感谢作者!

**Comment by aa335418265** [comment]
同样的问题！！把域名换成www.baidu.com 貌似就解决了

**Comment by dustturtle** [comment]
master上的最新版本引入了double check机制，可以设置两个ping地址，通过双地址+重试来保证可靠性，欢迎体验，谢谢～

**Comment by Suksal** [comment]
一直在WiFi环境下，运行APP，偶尔会出现网络status == RealStatusNotReachable的状态,  把域名换成www.baidu.com , 解决以上问题，但是，明明在wifi 环境下，却显示的是4G 环境。。。。。怎么修正？
