### ISSUE TITLE
FSMEngine currentStateID 线程不安全

### ISSUE THREAD

**Issue by mk-wang** [dustturtle/RealReachability#81]
开启xcode的thread sanitizer容易测出来
修改很简单nonatomic属性变成atomic的

<img width="510" alt="screen shot 2017-03-27 at 14 36 48" src="https://cloud.githubusercontent.com/assets/700254/24343819/ffd5647a-12fa-11e7-984b-f6550a9520bd.png">
<img width="402" alt="screen shot 2017-03-27 at 14 34 15" src="https://cloud.githubusercontent.com/assets/700254/24343821/06d6ce44-12fb-11e7-9e43-3b276379762d.png">

**Comment by dustturtle** [comment]
这是一个值类型的属性，不是对象，对其的实际操作应该是不耗时的，个人感觉这里的data race只是理论上。目前没有在实际使用中发现这里有引发问题，暂时不作修改
