### ISSUE TITLE
应用初始化时，检测真实网络状态，大概有5%的概率发生检测的结果错误。

### ISSUE THREAD

**Issue by changelee82** [dustturtle/RealReachability#83]
[[NSNotificationCenter defaultCenter] addObserver:self
                                                 selector:@selector(networkChanged:)
                                                     name:kRealReachabilityChangedNotification
                                                   object:nil];
- (void)networkChanged:(NSNotification *)notification
{
    RealReachability *reachability = (RealReachability *)notification.object;
    ReachabilityStatus status = [reachability currentReachabilityStatus];
在这里，开启20次应用，大约有一次status等于0。
}

但是从打印信息来看，永远都是 localConnectionInitializedStatus:2，网络状态并没有改变，不知是否我的写法有问题？谢谢。
iphone6p,iOS10.3.1

**Comment by dustturtle** [comment]
[GLobalRealReachability startNotifier]; 在didFinishLaunchingWithOptions里面调用了吗？

**Comment by changelee82** [comment]
调用了，然后就立刻在一个全局对象的init中调用上面的代码开启检测。

**Comment by dustturtle** [comment]
localConnectionInitializedStatus 表明本地网络初始化的状态是ok的， 你说的这种情况很大的可能是ping失败了
