### ISSUE TITLE
多次stopNotifier + startNotifier后，ping任务会变得很多. 以及一些线程同步的问题

### ISSUE THREAD

**Issue by jackieyk** [dustturtle/RealReachability#85]
1. startNotifier 最好@synchronize保护一下，以便多个线程同时调它也是安全的（这个改动成本不高哈，建议支持一下）
2.stopNotifier 最好能停掉ping任务（现在是基于gcd的，可能要改为NSOperationQueue, 不过还是希望能支持一下）
为什么要stopNotifier + startNotifier多次？我的场景是这样的：
当某次ping timeout后，网络会变为unreachable, 之后要至少等18s才能做下次检查。但是有时网络会卡一下，这次unreachable可能是误报。所以我希望在发现网络不通时，能更快地进行网络ping检查（比如1s一次）。因为RealReachability没提供这个接口，所以我就stop+start来触发新的ping.
当网络不通时更快地ping应该是对性能没什么损耗的，因为本来就不通，也不怕费流量了。
建议把ping任务做成基于NSOperationQueue的，当队列里有ping task时，startNotifier时就不用加个新的task了。

**Comment by dustturtle** [comment]
这块的建议挺好的，实际我觉得更合理的方案是加入优化重试的机制。笔者实在是够懒工作也比较忙，没有及时的实现这块内容。也鼓励有兴趣、有时间、有能力的同学优化实现，在充分测试的基础上来pull request

**Comment by lianleven** [comment]
@jackieyk 这个需求不需要一直去start，stop，网络监听只需要执行一次就可以了。在网络不通的情况下想保证快速连续ping的话，写一个定时操作执行reachabilityWithBlock这个方法。或者用[self performSelector:<#(nonnull SEL)#> withObject:<#(nullable id)#> afterDelay:<#(NSTimeInterval)#>];递归去执行reachabilityWithBlock。有网络的时候[NSObject cancelPreviousPerformRequestsWithTarget:<#(nonnull id)#> selector:<#(nonnull SEL)#> object:<#(nullable id)#>]取消这个，打破递归。

**Comment by dustturtle** [comment]
master上的最新版本引入了double check机制，可以设置两个ping地址，通过双地址+重试来保证可靠性，欢迎体验，谢谢～
