### ISSUE TITLE
Compile error in Xcode9 Beta3

### ISSUE THREAD

**Issue by Daemonson** [dustturtle/RealReachability#88]
![image](https://user-images.githubusercontent.com/7628550/28258332-4eae6d52-6b03-11e7-80a9-f83216e3692a.png)

**Comment by leavenstee** [comment]
for test purpose just commenting out those lines compiles works, seeking other solutions for the future thought

**Comment by Daemonson** [comment]
@leavenstee In the <AssertMacros.h> file,  Apple notes that macOS High Sierra and iOS 11 will now require that clients move to the new macros. As follows:
> /*

> For time immemorial, Mac OS X has defined version of most of these macros without the __ prefix, which
> could collide with similarly named functions or macros in user code, including new functionality in
> Boost and the C++ standard library.
> macOS High Sierra and iOS 11 will now require that clients move to the new macros as defined above.
> If you would like to enable the macros for use within your own project, you can define the
> __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES macro via an Xcode Build Configuration.
> See "Add a build configuration (xcconfig) file" in Xcode Help.
> To aid users of these macros in converting their sources, the following tops script will convert usages
> of the old macros into the new equivalents. To do so, in Terminal go into the directory containing the
> sources to be converted and run this command.
> find . -name '*.[c|cc|cp|cpp|m|mm|h]' -print0 | xargs -0 tops -verbose 
> replace "check()" with "__Check()" 
> replace "check_noerr()" with "__Check_noErr()" 
> replace "check_noerr_string()" with "__Check_noErr_String()" 
> replace "check_string()" with "__Check_String()" 
> replace "require()" with "__Require()" 
> replace "require_action()" with "__Require_Action()" 
> replace "require_action_string()" with "__Require_Action_String()" 
> replace "require_noerr()" with "__Require_noErr()" 
> replace "require_noerr_action()" with "__Require_noErr_Action()" 
> replace "require_noerr_action_string()" with "__Require_noErr_Action_String()" 
> replace "require_noerr_string()" with "__Require_noErr_String()" 
> replace "require_string()" with "__Require_String()" 
> replace "verify()" with "__Verify()" 
> replace "verify_action()" with "__Verify_Action()" 
> replace "verify_noerr()" with "__Verify_noErr()" 
> replace "verify_noerr_action()" with "__Verify_noErr_Action()" 
> replace "verify_noerr_string()" with "__Verify_noErr_String()" 
> replace "verify_string()" with "__Verify_String()" 
> replace "ncheck()" with "__nCheck()" 
> replace "ncheck_string()" with "__nCheck_String()" 
> replace "nrequire()" with "__nRequire()" 
> replace "nrequire_action()" with "__nRequire_Action()" 
> replace "nrequire_action_quiet()" with "__nRequire_Action_Quiet()" 
> replace "nrequire_action_string()" with "__nRequire_Action_String()" 
> replace "nrequire_quiet()" with "__nRequire_Quiet()" 
> replace "nrequire_string()" with "__nRequire_String()" 
> replace "nverify()" with "__nVerify()" 
> replace "nverify_string()" with "__nVerify_String()" 
> replace "require_action_quiet()" with "__Require_Action_Quiet()" 
> replace "require_noerr_action_quiet()" with "__Require_noErr_Action_Quiet()" 
> replace "require_noerr_quiet()" with "__Require_noErr_Quiet()" 
> replace "require_quiet()" with "__Require_Quiet()" 
> replace "check_compile_time()" with "__Check_Compile_Time()" 
> replace "debug_string()" with "__Debug_String()"
> */
