### ISSUE TITLE
切换网络时偶尔回调 无连接

### ISSUE THREAD

**Issue by BarryGuo** [dustturtle/RealReachability#9]
![0e7dc026-8ea7-4f6a-ac38-34df01c071c6](https://cloud.githubusercontent.com/assets/16474028/13521382/07f591de-e223-11e5-9f35-b2da6293eea0.png)
在网络切换中，偶尔会回调 无连接，建议在增加在前一次未ping通的情况，再ping一次

**Comment by dustturtle** [comment]
目前优化方案已经出炉，晚些时候开发提交上来,敬请期待~ 谢谢您的支持！（优化点已经使用TODO的形式记录在工程中并提交到了master）

**Comment by Brances** [comment]
我也遇到了类似的问题

**Comment by XB-Paul** [comment]
更新到最新的版本1.1.2，还是存在同样的问题。而且reachabilityWithBlock这个方法设置的block在网络变化时没有被调用。 我想在新的项目中使用这个类库来检测网络，希望楼主能优化下

**Comment by dustturtle** [comment]
reachabilitywithblock这个回调是单次触发式的，后面的变化不会调用，需要监听通知。这个issue目前还存在，最近有些事耽搁了，会尽快抽时间优化，不会辜负大家的期望！谢谢支持和关注！

**Comment by chengxianghe** [comment]
我也遇到了这个问题

**Comment by dustturtle** [comment]
已作优化，请使用master版本测试，谢谢！
