### ISSUE TITLE
Build faild in Xcode9！

### ISSUE THREAD

**Issue by hjw6160602** [dustturtle/RealReachability#91]
PingFoundation.h file failed in lines:

check_compile_time(sizeof(ICMPHeader) == 8);
check_compile_time(offsetof(ICMPHeader, type) == 0);
check_compile_time(offsetof(ICMPHeader, code) == 1);
check_compile_time(offsetof(ICMPHeader, checksum) == 2);
check_compile_time(offsetof(ICMPHeader, identifier) == 4);
check_compile_time(offsetof(ICMPHeader, sequenceNumber) == 6);

**Comment by luoshihui** [comment]
check_compile_time  should be __Check_Compile_Time.

**Comment by dustturtle** [comment]
#89 already fixed, please update~

**Comment by luoshihui** [comment]
Pod update with the old version

**Comment by dustturtle** [comment]
等过两天更新一个pod版本哈，目前可以用master上的最新版本，谢谢

**Comment by dustturtle** [comment]
pod version 1.1.9 updated, please try~ @luoshihui @hjw6160602

**Comment by hjw6160602** [comment]
OK, Thank you very much.
