### ISSUE TITLE
Xcode 9.0 beta5 多处报错

### ISSUE THREAD

**Issue by NobelLiu** [dustturtle/RealReachability#93]
编译不能通过

**Comment by dustturtle** [comment]
报错信息贴上来看看呢？

**Comment by dustturtle** [comment]
@NobelLiu

**Comment by NobelLiu** [comment]
![599d1e65e1a05.png](https://i.loli.net/2017/08/23/599d1e65e1a05.png)

**Comment by dustturtle** [comment]
你这个版本好像是老的？新版本已经解决这个问题了。相关的代码：
__Check_Compile_Time(sizeof(ICMPHeader) == 8);
__Check_Compile_Time(offsetof(ICMPHeader, type) == 0);
__Check_Compile_Time(offsetof(ICMPHeader, code) == 1);
__Check_Compile_Time(offsetof(ICMPHeader, checksum) == 2);
__Check_Compile_Time(offsetof(ICMPHeader, identifier) == 4);
__Check_Compile_Time(offsetof(ICMPHeader, sequenceNumber) == 6);

**Comment by dustturtle** [comment]
#91
