### ISSUE TITLE
iOS 9 运行报错

### ISSUE THREAD

**Issue by championship456** [dustturtle/RealReachability#96]
check_compile_time(sizeof(ICMPHeader) == 8);
check_compile_time(offsetof(ICMPHeader, type) == 0);
check_compile_time(offsetof(ICMPHeader, code) == 1);
check_compile_time(offsetof(ICMPHeader, checksum) == 2);
check_compile_time(offsetof(ICMPHeader, identifier) == 4);
check_compile_time(offsetof(ICMPHeader, sequenceNumber) == 6);

**Comment by summerHearts** [comment]
@championship456   一样

**Comment by summerHearts** [comment]
__Check_Compile_Time(sizeof(ICMPHeader) == 8);
__Check_Compile_Time(offsetof(ICMPHeader, type) == 0);
__Check_Compile_Time(offsetof(ICMPHeader, code) == 1);
__Check_Compile_Time(offsetof(ICMPHeader, checksum) == 2);
__Check_Compile_Time(offsetof(ICMPHeader, identifier) == 4);
__Check_Compile_Time(offsetof(ICMPHeader, sequenceNumber) == 6);

**Comment by summerHearts** [comment]
请这样做

**Comment by dustturtle** [comment]
是在真机运行报错吗？

**Comment by championship456** [comment]
真机和模拟器运行都会报错，报错1 Expected parameter declarator     2   Expected ')' 红点提示是这个函数sizeof(ICMPHeader) == 8

**Comment by dustturtle** [comment]
那看来要做一下兼容处理了，感谢反馈，会跟进处理🤝

**Comment by dustturtle** [comment]
最新版本的realreachability已经改成__Check_Compile_Time的方式了啊，请更新版本重试呢？

**Comment by championship456** [comment]
真机和模拟器都已经没有问题了

**Comment by dustturtle** [comment]
ok
