### ISSUE TITLE
iOS11报错

### ISSUE THREAD

**Issue by NoLiuxin** [dustturtle/RealReachability#97]
今天下载了Xcode9跑起来的时候报错，不知道是为什么呢？PingFoundation这个类
![aca65c6c-ddba-4fe7-a604-3f648eb38bfb](https://user-images.githubusercontent.com/8954358/30572128-895334ee-9cb1-11e7-8280-dd23017e1761.png)

**Comment by SanjiHo** [comment]
我也是 我刚刚今天更新得 有什么解决办法吗？

**Comment by dustturtle** [comment]
最新版本的pod应该没有这个问题了
