### ISSUE TITLE
RealReachability 在 Xcode 9 iOS 11 下，出现错误

### ISSUE THREAD

**Issue by YueLiXing** [dustturtle/RealReachability#98]
pods 导入，很多错误

**Comment by wangyuuuu** [comment]
pods 导入，很多错误

**Comment by qqppff1992** [comment]
pods 导入，很多错误

**Comment by vbonluk** [comment]
我的是直接放入项目的，也出现错误。
![qqqq](https://user-images.githubusercontent.com/7578155/30632411-8e97795a-9e1a-11e7-8324-09f225d74e52.png)
![2222](https://user-images.githubusercontent.com/7578155/30632426-97c710c6-9e1a-11e7-88cd-83938f04f5cc.png)

**Comment by vbonluk** [comment]
@所有遇到此问题的同学们。如果不急与上线产品，建议等待作者更新文件。急着上线的同学可以暂时用下面的方法来解决问题。后续等待作者更新即可。

修改 “check_compile_time” 为 “__Check_Compile_Time”

![333](https://user-images.githubusercontent.com/7578155/30632737-c92de0c6-9e1b-11e7-8e32-2e79d4a0eb2e.png)

**Comment by YueLiXing** [comment]
着急的话，别用 pod 导入，直接导入源码即可。。。

**Comment by emrealparslan93** [comment]
![screen shot 2017-09-21 at 17 56 54](https://user-images.githubusercontent.com/9310800/30702703-4c7b2648-9ef6-11e7-9c2c-fbf2648cca84.png)

Same here. Could you please comment in English ? :)

**Comment by SanjiHo** [comment]
我也是这样子 更新就报错了 如果改成__Check_Compile_Time 网络监测还有用吗？

**Comment by YueLiXing** [comment]
@SanjiHo san 可以的
@emrealparslan93 Please download the source code,and import it to your project. don't use the cocoapods to impprt it.

**Comment by SanjiHo** [comment]
OK 谢谢可以了




发自网易邮箱大师
在2017年09月22日 11:36，浮生若梦 写道：

@SanjiHo san 可以的
@emrealparslan93 Please download the source code,and import it to your project. don't use the cocoapods to impprt it.
